import { expect, test } from "../dev_deps.ts";
import { generate, mapperMap, modifierMap, theme } from "../mod.ts";

const expects: [string, string][] = [
  ["aspect-auto", ".aspect-auto{aspect-ratio:auto;}"],
  ["aspect-square", ".aspect-square{aspect-ratio:1 / 1;}"],
  ["aspect-video", ".aspect-video{aspect-ratio:16 / 9;}"],
  ["columns-1", ".columns-1{columns:1;}"],
  ["columns-10", ".columns-10{columns:10;}"],
  ["columns-auto", ".columns-auto{columns:auto;}"],
  ["columns-3xs", ".columns-3xs{columns:16rem;}"],
  ["columns-2xs", ".columns-2xs{columns:18rem;}"],
  ["columns-xs", ".columns-xs{columns:20rem;}"],
  ["columns-sm", ".columns-sm{columns:24rem;}"],
  ["columns-md", ".columns-md{columns:28rem;}"],
  ["columns-lg", ".columns-lg{columns:32rem;}"],
  ["columns-xl", ".columns-xl{columns:36rem;}"],
  ["columns-2xl", ".columns-2xl{columns:42rem;}"],
  ["columns-3xl", ".columns-3xl{columns:48rem;}"],
  ["columns-4xl", ".columns-4xl{columns:56rem;}"],
  ["columns-5xl", ".columns-5xl{columns:64rem;}"],
  ["columns-6xl", ".columns-6xl{columns:72rem;}"],
  ["columns-7xl", ".columns-7xl{columns:80rem;}"],
  ["break-after-auto", ".break-after-auto{break-after:auto;}"],
  ["break-after-avoid", ".break-after-avoid{break-after:avoid;}"],
  ["break-after-all", ".break-after-all{break-after:all;}"],
  [
    "break-after-avoid-page",
    ".break-after-avoid-page{break-after:avoid-page;}",
  ],
  ["break-after-page", ".break-after-page{break-after:page;}"],
  ["break-after-left", ".break-after-left{break-after:left;}"],
  ["break-after-right", ".break-after-right{break-after:right;}"],
  ["break-after-column", ".break-after-column{break-after:column;}"],
  ["break-before-auto", ".break-before-auto{break-before:auto;}"],
  ["break-before-avoid", ".break-before-avoid{break-before:avoid;}"],
  ["break-before-all", ".break-before-all{break-before:all;}"],
  [
    "break-before-avoid-page",
    ".break-before-avoid-page{break-before:avoid-page;}",
  ],
  ["break-before-page", ".break-before-page{break-before:page;}"],
  ["break-before-left", ".break-before-left{break-before:left;}"],
  ["break-before-right", ".break-before-right{break-before:right;}"],
  ["break-before-column", ".break-before-column{break-before:column;}"],
  ["break-inside-auto", ".break-inside-auto{break-inside:auto;}"],
  ["break-inside-avoid", ".break-inside-avoid{break-inside:avoid;}"],
  [
    "break-inside-avoid-page",
    ".break-inside-avoid-page{break-inside:avoid-page;}",
  ],
  [
    "break-inside-avoid-column",
    ".break-inside-avoid-column{break-inside:avoid-column;}",
  ],
  [
    "box-decoration-clone",
    ".box-decoration-clone{box-decoration-break:clone;}",
  ],
  [
    "box-decoration-slice",
    ".box-decoration-slice{box-decoration-break:slice;}",
  ],
  ["box-border", ".box-border{box-sizing:border-box;}"],
  ["box-content", ".box-content{box-sizing:content-box;}"],
  ["block", ".block{display:block;}"],
  ["inline-block", ".inline-block{display:inline-block;}"],
  ["inline", ".inline{display:inline;}"],
  ["flex", ".flex{display:flex;}"],
  ["inline-flex", ".inline-flex{display:inline-flex;}"],
  ["table", ".table{display:table;}"],
  ["inline-table", ".inline-table{display:inline-table;}"],
  ["table-caption", ".table-caption{display:table-caption;}"],
  // ["table-cell", ".table-cell{display:table-cell;}"],
  // ["table-column", ".table-column{display:table-column;}"],
  // ["table-column-group", ".table-column-group{display:table-column-group;}"],
  // ["table-footer-group", ".table-footer-group{display:table-footer-group;}"],
  // ["table-header-group", ".table-header-group{display:table-header-group;}"],
  // ["table-row-group", ".table-row-group{display:table-row-group;}"],
  // ["table-row", ".table-row{display:table-row;}"],
  // ["flow-root", ".flow-root{display:flow-root;}"],
  ["grid", ".grid{display:grid;}"],
  // ["inline-grid", ".inline-grid{display:inline-grid;}"],
  ["contents", ".contents{display:contents;}"],
  ["list-item", ".list-item{display:list-item;}"],
  ["hidden", ".hidden{display:none;}"],
  ["float-right", ".float-right{float:right;}"],
  ["float-left", ".float-left{float:left;}"],
  ["float-none", ".float-none{float:none;}"],
  ["clear-left", ".clear-left{clear:left;}"],
  ["clear-right", ".clear-right{clear:right;}"],
  ["clear-both", ".clear-both{clear:both;}"],
  ["clear-none", ".clear-none{clear:none;}"],
  ["isolate", ".isolate{isolation:isolate;}"],
  ["isolation-auto", ".isolation-auto{isolation:auto;}"],
  ["object-contain", ".object-contain{object-fit:contain;}"],
  ["object-cover", ".object-cover{object-fit:cover;}"],
  ["object-fill", ".object-fill{object-fit:fill;}"],
  ["object-none", ".object-none{object-fit:none;}"],
  ["object-scale-down", ".object-scale-down{object-fit:scale-down;}"],
  ["object-bottom", ".object-bottom{object-position:bottom;}"],
  ["object-center", ".object-center{object-position:center;}"],
  ["object-left", ".object-left{object-position:left;}"],
  ["object-right", ".object-right{object-position:right;}"],
  ["object-top", ".object-top{object-position:top;}"],
  [
    "object-right-bottom",
    ".object-right-bottom{object-position:right bottom;}",
  ],
  ["object-right-top", ".object-right-top{object-position:right top;}"],
  ["object-left-bottom", ".object-left-bottom{object-position:left bottom;}"],
  ["object-left-top", ".object-left-top{object-position:left top;}"],
  ["overflow-auto", ".overflow-auto{overflow:auto;}"],
  ["overflow-hidden", ".overflow-hidden{overflow:hidden;}"],
  ["overflow-clip", ".overflow-clip{overflow:clip;}"],
  ["overflow-visible", ".overflow-visible{overflow:visible;}"],
  ["overflow-scroll", ".overflow-scroll{overflow:scroll;}"],
  ["overflow-x-auto", ".overflow-x-auto{overflow-x:auto;}"],
  ["overflow-y-auto", ".overflow-y-auto{overflow-y:auto;}"],
  ["overflow-x-hidden", ".overflow-x-hidden{overflow-x:hidden;}"],
  ["overflow-y-hidden", ".overflow-y-hidden{overflow-y:hidden;}"],
  ["overflow-x-clip", ".overflow-x-clip{overflow-x:clip;}"],
  ["overflow-y-clip", ".overflow-y-clip{overflow-y:clip;}"],
  ["overflow-x-visible", ".overflow-x-visible{overflow-x:visible;}"],
  ["overflow-y-visible", ".overflow-y-visible{overflow-y:visible;}"],
  ["overflow-x-scroll", ".overflow-x-scroll{overflow-x:scroll;}"],
  ["overflow-y-scroll", ".overflow-y-scroll{overflow-y:scroll;}"],
  ["overscroll-auto", ".overscroll-auto{overscroll-behavior:auto;}"],
  ["overscroll-contain", ".overscroll-contain{overscroll-behavior:contain;}"],
  ["overscroll-none", ".overscroll-none{overscroll-behavior:none;}"],
  ["overscroll-y-auto", ".overscroll-y-auto{overscroll-behavior-y:auto;}"],
  [
    "overscroll-y-contain",
    ".overscroll-y-contain{overscroll-behavior-y:contain;}",
  ],
  ["overscroll-y-none", ".overscroll-y-none{overscroll-behavior-y:none;}"],
  ["overscroll-x-auto", ".overscroll-x-auto{overscroll-behavior-x:auto;}"],
  [
    "overscroll-x-contain",
    ".overscroll-x-contain{overscroll-behavior-x:contain;}",
  ],
  ["overscroll-x-none", ".overscroll-x-none{overscroll-behavior-x:none;}"],
  ["static", ".static{position:static;}"],
  ["fixed", ".fixed{position:fixed;}"],
  ["absolute", ".absolute{position:absolute;}"],
  ["relative", ".relative{position:relative;}"],
  ["sticky", ".sticky{position:sticky;}"],
  ["top-0", ".top-0{top:0px;}"],
  ["right-0", ".right-0{right:0px;}"],
  ["bottom-0", ".bottom-0{bottom:0px;}"],
  ["left-0", ".left-0{left:0px;}"],
  ["top-px", ".top-px{top:1px;}"],
  ["right-px", ".right-px{right:1px;}"],
  ["bottom-px", ".bottom-px{bottom:1px;}"],
  ["left-px", ".left-px{left:1px;}"],
  ["top-1", ".top-1{top:0.25rem;}"],
  ["right-1", ".right-1{right:0.25rem;}"],
  ["bottom-1", ".bottom-1{bottom:0.25rem;}"],
  ["left-1", ".left-1{left:0.25rem;}"],
  ["left-2", ".left-2{left:0.5rem;}"],
  ["top-2", ".top-2{top:0.5rem;}"],
  ["right-2", ".right-2{right:0.5rem;}"],
  ["bottom-2", ".bottom-2{bottom:0.5rem;}"],
  ["right-3", ".right-3{right:0.75rem;}"],
  ["bottom-3", ".bottom-3{bottom:0.75rem;}"],
  ["top-3", ".top-3{top:0.75rem;}"],
  ["top-4", ".top-4{top:1rem;}"],
  ["right-4", ".right-4{right:1rem;}"],
  ["bottom-4", ".bottom-4{bottom:1rem;}"],
  ["left-3", ".left-3{left:0.75rem;}"],
  ["left-4", ".left-4{left:1rem;}"],
  ["left-5", ".left-5{left:1.25rem;}"],
  ["left-6", ".left-6{left:1.5rem;}"],
  ["left-7", ".left-7{left:1.75rem;}"],
  ["left-8", ".left-8{left:2rem;}"],
  ["left-9", ".left-9{left:2.25rem;}"],
  ["left-10", ".left-10{left:2.5rem;}"],
  ["left-11", ".left-11{left:2.75rem;}"],
  ["left-12", ".left-12{left:3rem;}"],
  ["left-14", ".left-14{left:3.5rem;}"],
  ["top-5", ".top-5{top:1.25rem;}"],
  ["top-6", ".top-6{top:1.5rem;}"],
  ["top-7", ".top-7{top:1.75rem;}"],
  ["top-8", ".top-8{top:2rem;}"],
  ["top-9", ".top-9{top:2.25rem;}"],
  ["top-10", ".top-10{top:2.5rem;}"],
  ["top-11", ".top-11{top:2.75rem;}"],
  ["top-12", ".top-12{top:3rem;}"],
  ["top-14", ".top-14{top:3.5rem;}"],
  ["right-5", ".right-5{right:1.25rem;}"],
  ["right-6", ".right-6{right:1.5rem;}"],
  ["right-7", ".right-7{right:1.75rem;}"],
  ["right-8", ".right-8{right:2rem;}"],
  ["right-9", ".right-9{right:2.25rem;}"],
  ["right-10", ".right-10{right:2.5rem;}"],
  ["right-11", ".right-11{right:2.75rem;}"],
  ["right-12", ".right-12{right:3rem;}"],
  ["right-14", ".right-14{right:3.5rem;}"],
  ["bottom-5", ".bottom-5{bottom:1.25rem;}"],
  ["bottom-6", ".bottom-6{bottom:1.5rem;}"],
  ["bottom-7", ".bottom-7{bottom:1.75rem;}"],
  ["bottom-8", ".bottom-8{bottom:2rem;}"],
  ["bottom-9", ".bottom-9{bottom:2.25rem;}"],
  ["bottom-10", ".bottom-10{bottom:2.5rem;}"],
  ["bottom-11", ".bottom-11{bottom:2.75rem;}"],
  ["bottom-12", ".bottom-12{bottom:3rem;}"],
  ["bottom-14", ".bottom-14{bottom:3.5rem;}"],
  ["top-16", ".top-16{top:4rem;}"],
  ["right-16", ".right-16{right:4rem;}"],
  ["bottom-16", ".bottom-16{bottom:4rem;}"],
  ["left-16", ".left-16{left:4rem;}"],
  ["top-20", ".top-20{top:5rem;}"],
  ["right-20", ".right-20{right:5rem;}"],
  ["bottom-20", ".bottom-20{bottom:5rem;}"],
  ["left-20", ".left-20{left:5rem;}"],
  ["top-24", ".top-24{top:6rem;}"],
  ["right-24", ".right-24{right:6rem;}"],
  ["bottom-24", ".bottom-24{bottom:6rem;}"],
  ["left-24", ".left-24{left:6rem;}"],
  ["top-28", ".top-28{top:7rem;}"],
  ["right-28", ".right-28{right:7rem;}"],
  ["bottom-28", ".bottom-28{bottom:7rem;}"],
  ["left-28", ".left-28{left:7rem;}"],
  ["top-32", ".top-32{top:8rem;}"],
  ["right-32", ".right-32{right:8rem;}"],
  ["bottom-32", ".bottom-32{bottom:8rem;}"],
  ["left-32", ".left-32{left:8rem;}"],
  ["top-36", ".top-36{top:9rem;}"],
  ["right-36", ".right-36{right:9rem;}"],
  ["bottom-36", ".bottom-36{bottom:9rem;}"],
  ["left-36", ".left-36{left:9rem;}"],
  ["top-40", ".top-40{top:10rem;}"],
  ["right-40", ".right-40{right:10rem;}"],
  ["bottom-40", ".bottom-40{bottom:10rem;}"],
  ["left-40", ".left-40{left:10rem;}"],
  ["top-44", ".top-44{top:11rem;}"],
  ["right-44", ".right-44{right:11rem;}"],
  ["bottom-44", ".bottom-44{bottom:11rem;}"],
  ["left-44", ".left-44{left:11rem;}"],
  ["top-48", ".top-48{top:12rem;}"],
  ["right-48", ".right-48{right:12rem;}"],
  ["bottom-48", ".bottom-48{bottom:12rem;}"],
  ["left-48", ".left-48{left:12rem;}"],
  ["top-52", ".top-52{top:13rem;}"],
  ["right-52", ".right-52{right:13rem;}"],
  ["bottom-52", ".bottom-52{bottom:13rem;}"],
  ["left-52", ".left-52{left:13rem;}"],
  ["top-56", ".top-56{top:14rem;}"],
  ["right-56", ".right-56{right:14rem;}"],
  ["bottom-56", ".bottom-56{bottom:14rem;}"],
  ["left-56", ".left-56{left:14rem;}"],
  ["top-60", ".top-60{top:15rem;}"],
  ["right-60", ".right-60{right:15rem;}"],
  ["bottom-60", ".bottom-60{bottom:15rem;}"],
  ["left-60", ".left-60{left:15rem;}"],
  ["top-64", ".top-64{top:16rem;}"],
  ["right-64", ".right-64{right:16rem;}"],
  ["bottom-64", ".bottom-64{bottom:16rem;}"],
  ["left-64", ".left-64{left:16rem;}"],
  ["top-72", ".top-72{top:18rem;}"],
  ["right-72", ".right-72{right:18rem;}"],
  ["bottom-72", ".bottom-72{bottom:18rem;}"],
  ["left-72", ".left-72{left:18rem;}"],
  ["top-80", ".top-80{top:20rem;}"],
  ["right-80", ".right-80{right:20rem;}"],
  ["bottom-80", ".bottom-80{bottom:20rem;}"],
  ["left-80", ".left-80{left:20rem;}"],
  ["top-96", ".top-96{top:24rem;}"],
  ["right-96", ".right-96{right:24rem;}"],
  ["bottom-96", ".bottom-96{bottom:24rem;}"],
  ["left-96", ".left-96{left:24rem;}"],
  ["top-auto", ".top-auto{top:auto;}"],
  ["top-full", ".top-full{top:100%;}"],
  ["right-auto", ".right-auto{right:auto;}"],
  ["right-full", ".right-full{right:100%;}"],
  ["bottom-auto", ".bottom-auto{bottom:auto;}"],
  ["bottom-full", ".bottom-full{bottom:100%;}"],
  ["left-auto", ".left-auto{left:auto;}"],
  ["left-full", ".left-full{left:100%;}"],
  ["inset-x-0", ".inset-x-0{left:0px;right:0px;}"],
  ["inset-y-0", ".inset-y-0{bottom:0px;top:0px;}"],
  ["inset-x-px", ".inset-x-px{left:1px;right:1px;}"],
  ["inset-y-px", ".inset-y-px{bottom:1px;top:1px;}"],
  ["inset-x-1", ".inset-x-1{left:0.25rem;right:0.25rem;}"],
  ["inset-y-1", ".inset-y-1{bottom:0.25rem;top:0.25rem;}"],
  ["inset-x-2", ".inset-x-2{left:0.5rem;right:0.5rem;}"],
  ["inset-y-2", ".inset-y-2{bottom:0.5rem;top:0.5rem;}"],
  ["inset-x-3", ".inset-x-3{left:0.75rem;right:0.75rem;}"],
  ["inset-y-3", ".inset-y-3{bottom:0.75rem;top:0.75rem;}"],
  ["inset-x-4", ".inset-x-4{left:1rem;right:1rem;}"],
  ["inset-y-4", ".inset-y-4{bottom:1rem;top:1rem;}"],
  ["inset-x-5", ".inset-x-5{left:1.25rem;right:1.25rem;}"],
  ["inset-y-5", ".inset-y-5{bottom:1.25rem;top:1.25rem;}"],
  ["inset-x-6", ".inset-x-6{left:1.5rem;right:1.5rem;}"],
  ["inset-y-6", ".inset-y-6{bottom:1.5rem;top:1.5rem;}"],
  ["inset-x-7", ".inset-x-7{left:1.75rem;right:1.75rem;}"],
  ["inset-y-7", ".inset-y-7{bottom:1.75rem;top:1.75rem;}"],
  ["inset-x-8", ".inset-x-8{left:2rem;right:2rem;}"],
  ["inset-y-8", ".inset-y-8{bottom:2rem;top:2rem;}"],
  ["inset-x-9", ".inset-x-9{left:2.25rem;right:2.25rem;}"],
  ["inset-y-9", ".inset-y-9{bottom:2.25rem;top:2.25rem;}"],
  ["inset-x-10", ".inset-x-10{left:2.5rem;right:2.5rem;}"],
  ["inset-y-10", ".inset-y-10{bottom:2.5rem;top:2.5rem;}"],
  ["inset-x-11", ".inset-x-11{left:2.75rem;right:2.75rem;}"],
  ["inset-y-11", ".inset-y-11{bottom:2.75rem;top:2.75rem;}"],
  ["inset-x-12", ".inset-x-12{left:3rem;right:3rem;}"],
  ["inset-y-12", ".inset-y-12{bottom:3rem;top:3rem;}"],
  ["inset-x-14", ".inset-x-14{left:3.5rem;right:3.5rem;}"],
  ["inset-y-14", ".inset-y-14{bottom:3.5rem;top:3.5rem;}"],
  ["inset-x-16", ".inset-x-16{left:4rem;right:4rem;}"],
  ["inset-y-16", ".inset-y-16{bottom:4rem;top:4rem;}"],
  ["inset-x-20", ".inset-x-20{left:5rem;right:5rem;}"],
  ["inset-y-20", ".inset-y-20{bottom:5rem;top:5rem;}"],
  ["inset-x-24", ".inset-x-24{left:6rem;right:6rem;}"],
  ["inset-y-24", ".inset-y-24{bottom:6rem;top:6rem;}"],
  ["inset-x-28", ".inset-x-28{left:7rem;right:7rem;}"],
  ["inset-y-28", ".inset-y-28{bottom:7rem;top:7rem;}"],
  ["inset-x-32", ".inset-x-32{left:8rem;right:8rem;}"],
  ["inset-y-32", ".inset-y-32{bottom:8rem;top:8rem;}"],
  ["inset-x-36", ".inset-x-36{left:9rem;right:9rem;}"],
  ["inset-y-36", ".inset-y-36{bottom:9rem;top:9rem;}"],
  ["inset-x-40", ".inset-x-40{left:10rem;right:10rem;}"],
  ["inset-y-40", ".inset-y-40{bottom:10rem;top:10rem;}"],
  ["inset-x-44", ".inset-x-44{left:11rem;right:11rem;}"],
  ["inset-y-44", ".inset-y-44{bottom:11rem;top:11rem;}"],
  ["inset-x-48", ".inset-x-48{left:12rem;right:12rem;}"],
  ["inset-y-48", ".inset-y-48{bottom:12rem;top:12rem;}"],
  ["inset-x-52", ".inset-x-52{left:13rem;right:13rem;}"],
  ["inset-y-52", ".inset-y-52{bottom:13rem;top:13rem;}"],
  ["inset-x-56", ".inset-x-56{left:14rem;right:14rem;}"],
  ["inset-y-56", ".inset-y-56{bottom:14rem;top:14rem;}"],
  ["inset-x-60", ".inset-x-60{left:15rem;right:15rem;}"],
  ["inset-y-60", ".inset-y-60{bottom:15rem;top:15rem;}"],
  ["inset-x-64", ".inset-x-64{left:16rem;right:16rem;}"],
  ["inset-y-64", ".inset-y-64{bottom:16rem;top:16rem;}"],
  ["inset-x-72", ".inset-x-72{left:18rem;right:18rem;}"],
  ["inset-y-72", ".inset-y-72{bottom:18rem;top:18rem;}"],
  ["inset-x-80", ".inset-x-80{left:20rem;right:20rem;}"],
  ["inset-y-80", ".inset-y-80{bottom:20rem;top:20rem;}"],
  ["inset-x-96", ".inset-x-96{left:24rem;right:24rem;}"],
  ["inset-y-96", ".inset-y-96{bottom:24rem;top:24rem;}"],
  ["inset-x-auto", ".inset-x-auto{left:auto;right:auto;}"],
  ["inset-x-full", ".inset-x-full{left:100%;right:100%;}"],
  ["inset-y-auto", ".inset-y-auto{bottom:auto;top:auto;}"],
  ["inset-y-full", ".inset-y-full{bottom:100%;top:100%;}"],
  ["inset-x-0.5", ".inset-x-0\\.5{left:0.125rem;right:0.125rem;}"],
  ["inset-y-0.5", ".inset-y-0\\.5{bottom:0.125rem;top:0.125rem;}"],
  ["inset-x-1.5", ".inset-x-1\\.5{left:0.375rem;right:0.375rem;}"],
  ["inset-y-1.5", ".inset-y-1\\.5{bottom:0.375rem;top:0.375rem;}"],
  ["inset-x-2.5", ".inset-x-2\\.5{left:0.625rem;right:0.625rem;}"],
  ["inset-y-2.5", ".inset-y-2\\.5{bottom:0.625rem;top:0.625rem;}"],
  ["inset-x-3.5", ".inset-x-3\\.5{left:0.875rem;right:0.875rem;}"],
  ["inset-y-3.5", ".inset-y-3\\.5{bottom:0.875rem;top:0.875rem;}"],
  ["top-0.5", ".top-0\\.5{top:0.125rem;}"],
  ["right-0.5", ".right-0\\.5{right:0.125rem;}"],
  ["bottom-0.5", ".bottom-0\\.5{bottom:0.125rem;}"],
  ["left-0.5", ".left-0\\.5{left:0.125rem;}"],
  ["top-1.5", ".top-1\\.5{top:0.375rem;}"],
  ["right-1.5", ".right-1\\.5{right:0.375rem;}"],
  ["bottom-1.5", ".bottom-1\\.5{bottom:0.375rem;}"],
  ["left-1.5", ".left-1\\.5{left:0.375rem;}"],
  ["top-2.5", ".top-2\\.5{top:0.625rem;}"],
  ["right-2.5", ".right-2\\.5{right:0.625rem;}"],
  ["bottom-2.5", ".bottom-2\\.5{bottom:0.625rem;}"],
  ["left-2.5", ".left-2\\.5{left:0.625rem;}"],
  ["top-3.5", ".top-3\\.5{top:0.875rem;}"],
  ["right-3.5", ".right-3\\.5{right:0.875rem;}"],
  ["bottom-3.5", ".bottom-3\\.5{bottom:0.875rem;}"],
  ["left-3.5", ".left-3\\.5{left:0.875rem;}"],
  [
    "inset-0.5",
    ".inset-0\\.5{bottom:0.125rem;left:0.125rem;right:0.125rem;top:0.125rem;}",
  ],
  [
    "inset-1.5",
    ".inset-1\\.5{bottom:0.375rem;left:0.375rem;right:0.375rem;top:0.375rem;}",
  ],
  [
    "inset-2.5",
    ".inset-2\\.5{bottom:0.625rem;left:0.625rem;right:0.625rem;top:0.625rem;}",
  ],
  [
    "inset-3.5",
    ".inset-3\\.5{bottom:0.875rem;left:0.875rem;right:0.875rem;top:0.875rem;}",
  ],
  ["inset-0", ".inset-0{bottom:0px;left:0px;right:0px;top:0px;}"],
  ["inset-px", ".inset-px{bottom:1px;left:1px;right:1px;top:1px;}"],
  [
    "inset-1",
    ".inset-1{bottom:0.25rem;left:0.25rem;right:0.25rem;top:0.25rem;}",
  ],
  ["inset-2", ".inset-2{bottom:0.5rem;left:0.5rem;right:0.5rem;top:0.5rem;}"],
  [
    "inset-3",
    ".inset-3{bottom:0.75rem;left:0.75rem;right:0.75rem;top:0.75rem;}",
  ],
  ["inset-4", ".inset-4{bottom:1rem;left:1rem;right:1rem;top:1rem;}"],
  [
    "inset-5",
    ".inset-5{bottom:1.25rem;left:1.25rem;right:1.25rem;top:1.25rem;}",
  ],
  ["inset-6", ".inset-6{bottom:1.5rem;left:1.5rem;right:1.5rem;top:1.5rem;}"],
  [
    "inset-7",
    ".inset-7{bottom:1.75rem;left:1.75rem;right:1.75rem;top:1.75rem;}",
  ],
  ["inset-8", ".inset-8{bottom:2rem;left:2rem;right:2rem;top:2rem;}"],
  [
    "inset-9",
    ".inset-9{bottom:2.25rem;left:2.25rem;right:2.25rem;top:2.25rem;}",
  ],
  ["inset-10", ".inset-10{bottom:2.5rem;left:2.5rem;right:2.5rem;top:2.5rem;}"],
  [
    "inset-11",
    ".inset-11{bottom:2.75rem;left:2.75rem;right:2.75rem;top:2.75rem;}",
  ],
  ["inset-12", ".inset-12{bottom:3rem;left:3rem;right:3rem;top:3rem;}"],
  ["inset-14", ".inset-14{bottom:3.5rem;left:3.5rem;right:3.5rem;top:3.5rem;}"],
  ["inset-16", ".inset-16{bottom:4rem;left:4rem;right:4rem;top:4rem;}"],
  ["inset-20", ".inset-20{bottom:5rem;left:5rem;right:5rem;top:5rem;}"],
  ["inset-24", ".inset-24{bottom:6rem;left:6rem;right:6rem;top:6rem;}"],
  ["inset-28", ".inset-28{bottom:7rem;left:7rem;right:7rem;top:7rem;}"],
  ["inset-32", ".inset-32{bottom:8rem;left:8rem;right:8rem;top:8rem;}"],
  ["inset-36", ".inset-36{bottom:9rem;left:9rem;right:9rem;top:9rem;}"],
  ["inset-40", ".inset-40{bottom:10rem;left:10rem;right:10rem;top:10rem;}"],
  ["inset-44", ".inset-44{bottom:11rem;left:11rem;right:11rem;top:11rem;}"],
  ["inset-48", ".inset-48{bottom:12rem;left:12rem;right:12rem;top:12rem;}"],
  ["inset-52", ".inset-52{bottom:13rem;left:13rem;right:13rem;top:13rem;}"],
  ["inset-56", ".inset-56{bottom:14rem;left:14rem;right:14rem;top:14rem;}"],
  ["inset-60", ".inset-60{bottom:15rem;left:15rem;right:15rem;top:15rem;}"],
  ["inset-64", ".inset-64{bottom:16rem;left:16rem;right:16rem;top:16rem;}"],
  ["inset-72", ".inset-72{bottom:18rem;left:18rem;right:18rem;top:18rem;}"],
  ["inset-80", ".inset-80{bottom:20rem;left:20rem;right:20rem;top:20rem;}"],
  ["inset-96", ".inset-96{bottom:24rem;left:24rem;right:24rem;top:24rem;}"],
  ["inset-auto", ".inset-auto{bottom:auto;left:auto;right:auto;top:auto;}"],
  ["inset-full", ".inset-full{bottom:100%;left:100%;right:100%;top:100%;}"],
  ["top-1/2", ".top-1\\/2{top:50%;}"],
  ["top-1/3", ".top-1\\/3{top:33.33333333333333%;}"],
  ["top-2/3", ".top-2\\/3{top:66.66666666666666%;}"],
  ["top-1/4", ".top-1\\/4{top:25%;}"],
  ["top-2/4", ".top-2\\/4{top:50%;}"],
  ["top-3/4", ".top-3\\/4{top:75%;}"],
  ["right-1/2", ".right-1\\/2{right:50%;}"],
  ["right-1/3", ".right-1\\/3{right:33.33333333333333%;}"],
  ["right-2/3", ".right-2\\/3{right:66.66666666666666%;}"],
  ["right-1/4", ".right-1\\/4{right:25%;}"],
  ["right-2/4", ".right-2\\/4{right:50%;}"],
  ["right-3/4", ".right-3\\/4{right:75%;}"],
  ["bottom-1/2", ".bottom-1\\/2{bottom:50%;}"],
  ["bottom-1/3", ".bottom-1\\/3{bottom:33.33333333333333%;}"],
  ["bottom-2/3", ".bottom-2\\/3{bottom:66.66666666666666%;}"],
  ["bottom-1/4", ".bottom-1\\/4{bottom:25%;}"],
  ["bottom-2/4", ".bottom-2\\/4{bottom:50%;}"],
  ["bottom-3/4", ".bottom-3\\/4{bottom:75%;}"],
  ["left-1/2", ".left-1\\/2{left:50%;}"],
  ["left-1/3", ".left-1\\/3{left:33.33333333333333%;}"],
  ["left-2/3", ".left-2\\/3{left:66.66666666666666%;}"],
  ["left-1/4", ".left-1\\/4{left:25%;}"],
  ["left-2/4", ".left-2\\/4{left:50%;}"],
  ["left-3/4", ".left-3\\/4{left:75%;}"],
  ["inset-1/2", ".inset-1\\/2{bottom:50%;left:50%;right:50%;top:50%;}"],
  [
    "inset-1/3",
    ".inset-1\\/3{bottom:33.33333333333333%;left:33.33333333333333%;right:33.33333333333333%;top:33.33333333333333%;}",
  ],
  [
    "inset-2/3",
    ".inset-2\\/3{bottom:66.66666666666666%;left:66.66666666666666%;right:66.66666666666666%;top:66.66666666666666%;}",
  ],
  ["inset-1/4", ".inset-1\\/4{bottom:25%;left:25%;right:25%;top:25%;}"],
  ["inset-2/4", ".inset-2\\/4{bottom:50%;left:50%;right:50%;top:50%;}"],
  ["inset-3/4", ".inset-3\\/4{bottom:75%;left:75%;right:75%;top:75%;}"],
  ["inset-x-1/2", ".inset-x-1\\/2{left:50%;right:50%;}"],
  [
    "inset-x-1/3",
    ".inset-x-1\\/3{left:33.33333333333333%;right:33.33333333333333%;}",
  ],
  [
    "inset-x-2/3",
    ".inset-x-2\\/3{left:66.66666666666666%;right:66.66666666666666%;}",
  ],
  ["inset-x-1/4", ".inset-x-1\\/4{left:25%;right:25%;}"],
  ["inset-x-2/4", ".inset-x-2\\/4{left:50%;right:50%;}"],
  ["inset-x-3/4", ".inset-x-3\\/4{left:75%;right:75%;}"],
  ["inset-y-1/2", ".inset-y-1\\/2{bottom:50%;top:50%;}"],
  [
    "inset-y-1/3",
    ".inset-y-1\\/3{bottom:33.33333333333333%;top:33.33333333333333%;}",
  ],
  [
    "inset-y-2/3",
    ".inset-y-2\\/3{bottom:66.66666666666666%;top:66.66666666666666%;}",
  ],
  ["inset-y-1/4", ".inset-y-1\\/4{bottom:25%;top:25%;}"],
  ["inset-y-2/4", ".inset-y-2\\/4{bottom:50%;top:50%;}"],
  ["inset-y-3/4", ".inset-y-3\\/4{bottom:75%;top:75%;}"],
  ["inset-[3px]", ".inset-\\[3px\\]{bottom:3px;left:3px;right:3px;top:3px;}"],
  ["inset-x-[3px]", ".inset-x-\\[3px\\]{left:3px;right:3px;}"],
  ["inset-y-[3px]", ".inset-y-\\[3px\\]{bottom:3px;top:3px;}"],
  ["top-[3px]", ".top-\\[3px\\]{top:3px;}"],
  ["left-[3px]", ".left-\\[3px\\]{left:3px;}"],
  ["right-[3px]", ".right-\\[3px\\]{right:3px;}"],
  ["bottom-[3px]", ".bottom-\\[3px\\]{bottom:3px;}"],
  ["visible", ".visible{visibility:visible;}"],
  ["invisible", ".invisible{visibility:hidden;}"],
  ["z-0", ".z-0{z-index:0;}"],
  ["z-10", ".z-10{z-index:10;}"],
  ["z-20", ".z-20{z-index:20;}"],
  ["z-30", ".z-30{z-index:30;}"],
  ["z-40", ".z-40{z-index:40;}"],
  ["z-50", ".z-50{z-index:50;}"],
  ["z-auto", ".z-auto{z-index:auto;}"],
  ["flex-1", ".flex-1{flex:1 1 0%;}"],
  ["flex-auto", ".flex-auto{flex:1 1 auto;}"],
  ["flex-initial", ".flex-initial{flex:0 1 auto;}"],
  ["flex-none", ".flex-none{flex:none;}"],
  ["justify-start", ".justify-start{justify-content:flex-start;}"],
  ["justify-end", ".justify-end{justify-content:flex-end;}"],
  ["justify-center", ".justify-center{justify-content:center;}"],
  ["justify-between", ".justify-between{justify-content:space-between;}"],
  ["justify-around", ".justify-around{justify-content:space-around;}"],
  ["justify-evenly", ".justify-evenly{justify-content:space-evenly;}"],
  ["justify-start", ".justify-start{justify-content:flex-start;}"],
  ["justify-end", ".justify-end{justify-content:flex-end;}"],
  ["justify-center", ".justify-center{justify-content:center;}"],
  ["justify-between", ".justify-between{justify-content:space-between;}"],
  ["justify-around", ".justify-around{justify-content:space-around;}"],
  ["justify-evenly", ".justify-evenly{justify-content:space-evenly;}"],
  ["justify-self-auto", ".justify-self-auto{justify-self:auto;}"],
  ["justify-self-start", ".justify-self-start{justify-self:start;}"],
  ["justify-self-end", ".justify-self-end{justify-self:end;}"],
  ["justify-self-center", ".justify-self-center{justify-self:center;}"],
  ["justify-self-stretch", ".justify-self-stretch{justify-self:stretch;}"],
  ["content-center", ".content-center{align-content:center;}"],
  ["content-start", ".content-start{align-content:flex-start;}"],
  ["content-end", ".content-end{align-content:flex-end;}"],
  ["content-between", ".content-between{align-content:space-between;}"],
  ["content-around", ".content-around{align-content:space-around;}"],
  ["content-evenly", ".content-evenly{align-content:space-evenly;}"],
  ["content-center", ".content-center{align-content:center;}"],
  ["content-start", ".content-start{align-content:flex-start;}"],
  ["content-end", ".content-end{align-content:flex-end;}"],
  ["content-between", ".content-between{align-content:space-between;}"],
  ["content-around", ".content-around{align-content:space-around;}"],
  ["content-evenly", ".content-evenly{align-content:space-evenly;}"],
  ["items-start", ".items-start{align-items:flex-start;}"],
  ["items-end", ".items-end{align-items:flex-end;}"],
  ["items-center", ".items-center{align-items:center;}"],
  ["items-baseline", ".items-baseline{align-items:baseline;}"],
  ["items-stretch", ".items-stretch{align-items:stretch;}"],
  ["m-0", ".m-0{margin:0px;}"],
  ["mx-0", ".mx-0{margin-left:0px;margin-right:0px;}"],
  ["my-0", ".my-0{margin-bottom:0px;margin-top:0px;}"],
  ["mt-0", ".mt-0{margin-top:0px;}"],
  ["mr-0", ".mr-0{margin-right:0px;}"],
  ["mb-0", ".mb-0{margin-bottom:0px;}"],
  ["ml-0", ".ml-0{margin-left:0px;}"],
  ["m-px", ".m-px{margin:1px;}"],
  ["mx-px", ".mx-px{margin-left:1px;margin-right:1px;}"],
  ["my-px", ".my-px{margin-bottom:1px;margin-top:1px;}"],
  ["mt-px", ".mt-px{margin-top:1px;}"],
  ["mr-px", ".mr-px{margin-right:1px;}"],
  ["mb-px", ".mb-px{margin-bottom:1px;}"],
  ["ml-px", ".ml-px{margin-left:1px;}"],
  ["m-1", ".m-1{margin:0.25rem;}"],
  ["mx-1", ".mx-1{margin-left:0.25rem;margin-right:0.25rem;}"],
  ["my-1", ".my-1{margin-bottom:0.25rem;margin-top:0.25rem;}"],
  ["mt-1", ".mt-1{margin-top:0.25rem;}"],
  ["mr-1", ".mr-1{margin-right:0.25rem;}"],
  ["mb-1", ".mb-1{margin-bottom:0.25rem;}"],
  ["ml-1", ".ml-1{margin-left:0.25rem;}"],
  ["m-2", ".m-2{margin:0.5rem;}"],
  ["mx-2", ".mx-2{margin-left:0.5rem;margin-right:0.5rem;}"],
  ["my-2", ".my-2{margin-bottom:0.5rem;margin-top:0.5rem;}"],
  ["mt-2", ".mt-2{margin-top:0.5rem;}"],
  ["mr-2", ".mr-2{margin-right:0.5rem;}"],
  ["mb-2", ".mb-2{margin-bottom:0.5rem;}"],
  ["ml-2", ".ml-2{margin-left:0.5rem;}"],
  ["m-3", ".m-3{margin:0.75rem;}"],
  ["mx-3", ".mx-3{margin-left:0.75rem;margin-right:0.75rem;}"],
  ["my-3", ".my-3{margin-bottom:0.75rem;margin-top:0.75rem;}"],
  ["mt-3", ".mt-3{margin-top:0.75rem;}"],
  ["mr-3", ".mr-3{margin-right:0.75rem;}"],
  ["mb-3", ".mb-3{margin-bottom:0.75rem;}"],
  ["ml-3", ".ml-3{margin-left:0.75rem;}"],
  ["m-4", ".m-4{margin:1rem;}"],
  ["mx-4", ".mx-4{margin-left:1rem;margin-right:1rem;}"],
  ["my-4", ".my-4{margin-bottom:1rem;margin-top:1rem;}"],
  ["mt-4", ".mt-4{margin-top:1rem;}"],
  ["mr-4", ".mr-4{margin-right:1rem;}"],
  ["mb-4", ".mb-4{margin-bottom:1rem;}"],
  ["ml-4", ".ml-4{margin-left:1rem;}"],
  ["m-5", ".m-5{margin:1.25rem;}"],
  ["mx-5", ".mx-5{margin-left:1.25rem;margin-right:1.25rem;}"],
  ["my-5", ".my-5{margin-bottom:1.25rem;margin-top:1.25rem;}"],
  ["mt-5", ".mt-5{margin-top:1.25rem;}"],
  ["mr-5", ".mr-5{margin-right:1.25rem;}"],
  ["mb-5", ".mb-5{margin-bottom:1.25rem;}"],
  ["ml-5", ".ml-5{margin-left:1.25rem;}"],
  ["m-6", ".m-6{margin:1.5rem;}"],
  ["mx-6", ".mx-6{margin-left:1.5rem;margin-right:1.5rem;}"],
  ["my-6", ".my-6{margin-bottom:1.5rem;margin-top:1.5rem;}"],
  ["mt-6", ".mt-6{margin-top:1.5rem;}"],
  ["mr-6", ".mr-6{margin-right:1.5rem;}"],
  ["mb-6", ".mb-6{margin-bottom:1.5rem;}"],
  ["ml-6", ".ml-6{margin-left:1.5rem;}"],
  ["m-7", ".m-7{margin:1.75rem;}"],
  ["mx-7", ".mx-7{margin-left:1.75rem;margin-right:1.75rem;}"],
  ["my-7", ".my-7{margin-bottom:1.75rem;margin-top:1.75rem;}"],
  ["mt-7", ".mt-7{margin-top:1.75rem;}"],
  ["mr-7", ".mr-7{margin-right:1.75rem;}"],
  ["mb-7", ".mb-7{margin-bottom:1.75rem;}"],
  ["ml-7", ".ml-7{margin-left:1.75rem;}"],
  ["m-8", ".m-8{margin:2rem;}"],
  ["mx-8", ".mx-8{margin-left:2rem;margin-right:2rem;}"],
  ["my-8", ".my-8{margin-bottom:2rem;margin-top:2rem;}"],
  ["mt-8", ".mt-8{margin-top:2rem;}"],
  ["mr-8", ".mr-8{margin-right:2rem;}"],
  ["mb-8", ".mb-8{margin-bottom:2rem;}"],
  ["ml-8", ".ml-8{margin-left:2rem;}"],
  ["m-9", ".m-9{margin:2.25rem;}"],
  ["mx-9", ".mx-9{margin-left:2.25rem;margin-right:2.25rem;}"],
  ["my-9", ".my-9{margin-bottom:2.25rem;margin-top:2.25rem;}"],
  ["mt-9", ".mt-9{margin-top:2.25rem;}"],
  ["mr-9", ".mr-9{margin-right:2.25rem;}"],
  ["mb-9", ".mb-9{margin-bottom:2.25rem;}"],
  ["ml-9", ".ml-9{margin-left:2.25rem;}"],
  ["m-10", ".m-10{margin:2.5rem;}"],
  ["mx-10", ".mx-10{margin-left:2.5rem;margin-right:2.5rem;}"],
  ["my-10", ".my-10{margin-bottom:2.5rem;margin-top:2.5rem;}"],
  ["mt-10", ".mt-10{margin-top:2.5rem;}"],
  ["mr-10", ".mr-10{margin-right:2.5rem;}"],
  ["mb-10", ".mb-10{margin-bottom:2.5rem;}"],
  ["ml-10", ".ml-10{margin-left:2.5rem;}"],
  ["m-11", ".m-11{margin:2.75rem;}"],
  ["mx-11", ".mx-11{margin-left:2.75rem;margin-right:2.75rem;}"],
  ["my-11", ".my-11{margin-bottom:2.75rem;margin-top:2.75rem;}"],
  ["mt-11", ".mt-11{margin-top:2.75rem;}"],
  ["mr-11", ".mr-11{margin-right:2.75rem;}"],
  ["mb-11", ".mb-11{margin-bottom:2.75rem;}"],
  ["ml-11", ".ml-11{margin-left:2.75rem;}"],
  ["m-12", ".m-12{margin:3rem;}"],
  ["mx-12", ".mx-12{margin-left:3rem;margin-right:3rem;}"],
  ["my-12", ".my-12{margin-bottom:3rem;margin-top:3rem;}"],
  ["mt-12", ".mt-12{margin-top:3rem;}"],
  ["mr-12", ".mr-12{margin-right:3rem;}"],
  ["mb-12", ".mb-12{margin-bottom:3rem;}"],
  ["ml-12", ".ml-12{margin-left:3rem;}"],
  ["m-14", ".m-14{margin:3.5rem;}"],
  ["mx-14", ".mx-14{margin-left:3.5rem;margin-right:3.5rem;}"],
  ["my-14", ".my-14{margin-bottom:3.5rem;margin-top:3.5rem;}"],
  ["mt-14", ".mt-14{margin-top:3.5rem;}"],
  ["mr-14", ".mr-14{margin-right:3.5rem;}"],
  ["mb-14", ".mb-14{margin-bottom:3.5rem;}"],
  ["ml-14", ".ml-14{margin-left:3.5rem;}"],
  ["m-16", ".m-16{margin:4rem;}"],
  ["mx-16", ".mx-16{margin-left:4rem;margin-right:4rem;}"],
  ["my-16", ".my-16{margin-bottom:4rem;margin-top:4rem;}"],
  ["mt-16", ".mt-16{margin-top:4rem;}"],
  ["mr-16", ".mr-16{margin-right:4rem;}"],
  ["mb-16", ".mb-16{margin-bottom:4rem;}"],
  ["ml-16", ".ml-16{margin-left:4rem;}"],
  ["m-20", ".m-20{margin:5rem;}"],
  ["mx-20", ".mx-20{margin-left:5rem;margin-right:5rem;}"],
  ["my-20", ".my-20{margin-bottom:5rem;margin-top:5rem;}"],
  ["mt-20", ".mt-20{margin-top:5rem;}"],
  ["mr-20", ".mr-20{margin-right:5rem;}"],
  ["mb-20", ".mb-20{margin-bottom:5rem;}"],
  ["ml-20", ".ml-20{margin-left:5rem;}"],
  ["m-24", ".m-24{margin:6rem;}"],
  ["mx-24", ".mx-24{margin-left:6rem;margin-right:6rem;}"],
  ["my-24", ".my-24{margin-bottom:6rem;margin-top:6rem;}"],
  ["mt-24", ".mt-24{margin-top:6rem;}"],
  ["mr-24", ".mr-24{margin-right:6rem;}"],
  ["mb-24", ".mb-24{margin-bottom:6rem;}"],
  ["ml-24", ".ml-24{margin-left:6rem;}"],
  ["m-28", ".m-28{margin:7rem;}"],
  ["mx-28", ".mx-28{margin-left:7rem;margin-right:7rem;}"],
  ["my-28", ".my-28{margin-bottom:7rem;margin-top:7rem;}"],
  ["mt-28", ".mt-28{margin-top:7rem;}"],
  ["mr-28", ".mr-28{margin-right:7rem;}"],
  ["mb-28", ".mb-28{margin-bottom:7rem;}"],
  ["ml-28", ".ml-28{margin-left:7rem;}"],
  ["m-32", ".m-32{margin:8rem;}"],
  ["mx-32", ".mx-32{margin-left:8rem;margin-right:8rem;}"],
  ["my-32", ".my-32{margin-bottom:8rem;margin-top:8rem;}"],
  ["mt-32", ".mt-32{margin-top:8rem;}"],
  ["mr-32", ".mr-32{margin-right:8rem;}"],
  ["mb-32", ".mb-32{margin-bottom:8rem;}"],
  ["ml-32", ".ml-32{margin-left:8rem;}"],
  ["m-36", ".m-36{margin:9rem;}"],
  ["mx-36", ".mx-36{margin-left:9rem;margin-right:9rem;}"],
  ["my-36", ".my-36{margin-bottom:9rem;margin-top:9rem;}"],
  ["mt-36", ".mt-36{margin-top:9rem;}"],
  ["mr-36", ".mr-36{margin-right:9rem;}"],
  ["mb-36", ".mb-36{margin-bottom:9rem;}"],
  ["ml-36", ".ml-36{margin-left:9rem;}"],
  ["m-40", ".m-40{margin:10rem;}"],
  ["mx-40", ".mx-40{margin-left:10rem;margin-right:10rem;}"],
  ["my-40", ".my-40{margin-bottom:10rem;margin-top:10rem;}"],
  ["mt-40", ".mt-40{margin-top:10rem;}"],
  ["mr-40", ".mr-40{margin-right:10rem;}"],
  ["mb-40", ".mb-40{margin-bottom:10rem;}"],
  ["ml-40", ".ml-40{margin-left:10rem;}"],
  ["m-44", ".m-44{margin:11rem;}"],
  ["mx-44", ".mx-44{margin-left:11rem;margin-right:11rem;}"],
  ["my-44", ".my-44{margin-bottom:11rem;margin-top:11rem;}"],
  ["mt-44", ".mt-44{margin-top:11rem;}"],
  ["mr-44", ".mr-44{margin-right:11rem;}"],
  ["mb-44", ".mb-44{margin-bottom:11rem;}"],
  ["ml-44", ".ml-44{margin-left:11rem;}"],
  ["m-48", ".m-48{margin:12rem;}"],
  ["mx-48", ".mx-48{margin-left:12rem;margin-right:12rem;}"],
  ["my-48", ".my-48{margin-bottom:12rem;margin-top:12rem;}"],
  ["mt-48", ".mt-48{margin-top:12rem;}"],
  ["mr-48", ".mr-48{margin-right:12rem;}"],
  ["mb-48", ".mb-48{margin-bottom:12rem;}"],
  ["ml-48", ".ml-48{margin-left:12rem;}"],
  ["m-52", ".m-52{margin:13rem;}"],
  ["mx-52", ".mx-52{margin-left:13rem;margin-right:13rem;}"],
  ["my-52", ".my-52{margin-bottom:13rem;margin-top:13rem;}"],
  ["mt-52", ".mt-52{margin-top:13rem;}"],
  ["mr-52", ".mr-52{margin-right:13rem;}"],
  ["mb-52", ".mb-52{margin-bottom:13rem;}"],
  ["ml-52", ".ml-52{margin-left:13rem;}"],
  ["m-56", ".m-56{margin:14rem;}"],
  ["mx-56", ".mx-56{margin-left:14rem;margin-right:14rem;}"],
  ["my-56", ".my-56{margin-bottom:14rem;margin-top:14rem;}"],
  ["mt-56", ".mt-56{margin-top:14rem;}"],
  ["mr-56", ".mr-56{margin-right:14rem;}"],
  ["mb-56", ".mb-56{margin-bottom:14rem;}"],
  ["ml-56", ".ml-56{margin-left:14rem;}"],
  ["m-60", ".m-60{margin:15rem;}"],
  ["mx-60", ".mx-60{margin-left:15rem;margin-right:15rem;}"],
  ["my-60", ".my-60{margin-bottom:15rem;margin-top:15rem;}"],
  ["mt-60", ".mt-60{margin-top:15rem;}"],
  ["mr-60", ".mr-60{margin-right:15rem;}"],
  ["mb-60", ".mb-60{margin-bottom:15rem;}"],
  ["ml-60", ".ml-60{margin-left:15rem;}"],
  ["m-64", ".m-64{margin:16rem;}"],
  ["mx-64", ".mx-64{margin-left:16rem;margin-right:16rem;}"],
  ["my-64", ".my-64{margin-bottom:16rem;margin-top:16rem;}"],
  ["mt-64", ".mt-64{margin-top:16rem;}"],
  ["mr-64", ".mr-64{margin-right:16rem;}"],
  ["mb-64", ".mb-64{margin-bottom:16rem;}"],
  ["ml-64", ".ml-64{margin-left:16rem;}"],
  ["m-72", ".m-72{margin:18rem;}"],
  ["mx-72", ".mx-72{margin-left:18rem;margin-right:18rem;}"],
  ["my-72", ".my-72{margin-bottom:18rem;margin-top:18rem;}"],
  ["mt-72", ".mt-72{margin-top:18rem;}"],
  ["mr-72", ".mr-72{margin-right:18rem;}"],
  ["mb-72", ".mb-72{margin-bottom:18rem;}"],
  ["ml-72", ".ml-72{margin-left:18rem;}"],
  ["m-80", ".m-80{margin:20rem;}"],
  ["mx-80", ".mx-80{margin-left:20rem;margin-right:20rem;}"],
  ["my-80", ".my-80{margin-bottom:20rem;margin-top:20rem;}"],
  ["mt-80", ".mt-80{margin-top:20rem;}"],
  ["mr-80", ".mr-80{margin-right:20rem;}"],
  ["mb-80", ".mb-80{margin-bottom:20rem;}"],
  ["ml-80", ".ml-80{margin-left:20rem;}"],
  ["m-96", ".m-96{margin:24rem;}"],
  ["mx-96", ".mx-96{margin-left:24rem;margin-right:24rem;}"],
  ["my-96", ".my-96{margin-bottom:24rem;margin-top:24rem;}"],
  ["mt-96", ".mt-96{margin-top:24rem;}"],
  ["mr-96", ".mr-96{margin-right:24rem;}"],
  ["mb-96", ".mb-96{margin-bottom:24rem;}"],
  ["ml-96", ".ml-96{margin-left:24rem;}"],
  ["m-auto", ".m-auto{margin:auto;}"],
  ["mx-auto", ".mx-auto{margin-left:auto;margin-right:auto;}"],
  ["my-auto", ".my-auto{margin-bottom:auto;margin-top:auto;}"],
  ["mt-auto", ".mt-auto{margin-top:auto;}"],
  ["mr-auto", ".mr-auto{margin-right:auto;}"],
  ["mb-auto", ".mb-auto{margin-bottom:auto;}"],
  ["ml-auto", ".ml-auto{margin-left:auto;}"],
  ["ml-auto", ".ml-auto{margin-left:auto;}"],
  ["m-0.5", ".m-0\\.5{margin:0.125rem;}"],
  ["mx-0.5", ".mx-0\\.5{margin-left:0.125rem;margin-right:0.125rem;}"],
  ["my-0.5", ".my-0\\.5{margin-bottom:0.125rem;margin-top:0.125rem;}"],
  ["mt-0.5", ".mt-0\\.5{margin-top:0.125rem;}"],
  ["mr-0.5", ".mr-0\\.5{margin-right:0.125rem;}"],
  ["mb-0.5", ".mb-0\\.5{margin-bottom:0.125rem;}"],
  ["ml-0.5", ".ml-0\\.5{margin-left:0.125rem;}"],
  ["m-1.5", ".m-1\\.5{margin:0.375rem;}"],
  ["mx-1.5", ".mx-1\\.5{margin-left:0.375rem;margin-right:0.375rem;}"],
  ["my-1.5", ".my-1\\.5{margin-bottom:0.375rem;margin-top:0.375rem;}"],
  ["mt-1.5", ".mt-1\\.5{margin-top:0.375rem;}"],
  ["mr-1.5", ".mr-1\\.5{margin-right:0.375rem;}"],
  ["mb-1.5", ".mb-1\\.5{margin-bottom:0.375rem;}"],
  ["ml-1.5", ".ml-1\\.5{margin-left:0.375rem;}"],
  ["m-2.5", ".m-2\\.5{margin:0.625rem;}"],
  ["mx-2.5", ".mx-2\\.5{margin-left:0.625rem;margin-right:0.625rem;}"],
  ["my-2.5", ".my-2\\.5{margin-bottom:0.625rem;margin-top:0.625rem;}"],
  ["mt-2.5", ".mt-2\\.5{margin-top:0.625rem;}"],
  ["mr-2.5", ".mr-2\\.5{margin-right:0.625rem;}"],
  ["mb-2.5", ".mb-2\\.5{margin-bottom:0.625rem;}"],
  ["ml-2.5", ".ml-2\\.5{margin-left:0.625rem;}"],
  ["m-3.5", ".m-3\\.5{margin:0.875rem;}"],
  ["mx-3.5", ".mx-3\\.5{margin-left:0.875rem;margin-right:0.875rem;}"],
  ["my-3.5", ".my-3\\.5{margin-bottom:0.875rem;margin-top:0.875rem;}"],
  ["mt-3.5", ".mt-3\\.5{margin-top:0.875rem;}"],
  ["mr-3.5", ".mr-3\\.5{margin-right:0.875rem;}"],
  ["mb-3.5", ".mb-3\\.5{margin-bottom:0.875rem;}"],
  ["ml-3.5", ".ml-3\\.5{margin-left:0.875rem;}"],
  ["m-[1px]", ".m-\\[1px\\]{margin:1px;}"],
  ["mx-[1px]", ".mx-\\[1px\\]{margin-left:1px;margin-right:1px;}"],
  ["my-[1px]", ".my-\\[1px\\]{margin-bottom:1px;margin-top:1px;}"],
  ["mt-[1px]", ".mt-\\[1px\\]{margin-top:1px;}"],
  ["ml-[1px]", ".ml-\\[1px\\]{margin-left:1px;}"],
  ["mb-[1px]", ".mb-\\[1px\\]{margin-bottom:1px;}"],
  ["mr-[1px]", ".mr-\\[1px\\]{margin-right:1px;}"],
  ["p-0", ".p-0{padding:0px;}"],
  ["px-0", ".px-0{padding-left:0px;padding-right:0px;}"],
  ["py-0", ".py-0{padding-bottom:0px;padding-top:0px;}"],
  ["pt-0", ".pt-0{padding-top:0px;}"],
  ["pr-0", ".pr-0{padding-right:0px;}"],
  ["pb-0", ".pb-0{padding-bottom:0px;}"],
  ["pl-0", ".pl-0{padding-left:0px;}"],
  ["p-px", ".p-px{padding:1px;}"],
  ["px-px", ".px-px{padding-left:1px;padding-right:1px;}"],
  ["py-px", ".py-px{padding-bottom:1px;padding-top:1px;}"],
  ["pt-px", ".pt-px{padding-top:1px;}"],
  ["pr-px", ".pr-px{padding-right:1px;}"],
  ["pb-px", ".pb-px{padding-bottom:1px;}"],
  ["pl-px", ".pl-px{padding-left:1px;}"],
  ["p-1", ".p-1{padding:0.25rem;}"],
  ["px-1", ".px-1{padding-left:0.25rem;padding-right:0.25rem;}"],
  ["py-1", ".py-1{padding-bottom:0.25rem;padding-top:0.25rem;}"],
  ["pt-1", ".pt-1{padding-top:0.25rem;}"],
  ["pr-1", ".pr-1{padding-right:0.25rem;}"],
  ["pb-1", ".pb-1{padding-bottom:0.25rem;}"],
  ["pl-1", ".pl-1{padding-left:0.25rem;}"],
  ["p-2", ".p-2{padding:0.5rem;}"],
  ["px-2", ".px-2{padding-left:0.5rem;padding-right:0.5rem;}"],
  ["py-2", ".py-2{padding-bottom:0.5rem;padding-top:0.5rem;}"],
  ["pt-2", ".pt-2{padding-top:0.5rem;}"],
  ["pr-2", ".pr-2{padding-right:0.5rem;}"],
  ["pb-2", ".pb-2{padding-bottom:0.5rem;}"],
  ["pl-2", ".pl-2{padding-left:0.5rem;}"],
  ["p-3", ".p-3{padding:0.75rem;}"],
  ["px-3", ".px-3{padding-left:0.75rem;padding-right:0.75rem;}"],
  ["py-3", ".py-3{padding-bottom:0.75rem;padding-top:0.75rem;}"],
  ["pt-3", ".pt-3{padding-top:0.75rem;}"],
  ["pr-3", ".pr-3{padding-right:0.75rem;}"],
  ["pb-3", ".pb-3{padding-bottom:0.75rem;}"],
  ["pl-3", ".pl-3{padding-left:0.75rem;}"],
  ["p-4", ".p-4{padding:1rem;}"],
  ["px-4", ".px-4{padding-left:1rem;padding-right:1rem;}"],
  ["py-4", ".py-4{padding-bottom:1rem;padding-top:1rem;}"],
  ["pt-4", ".pt-4{padding-top:1rem;}"],
  ["pr-4", ".pr-4{padding-right:1rem;}"],
  ["pb-4", ".pb-4{padding-bottom:1rem;}"],
  ["pl-4", ".pl-4{padding-left:1rem;}"],
  ["p-5", ".p-5{padding:1.25rem;}"],
  ["px-5", ".px-5{padding-left:1.25rem;padding-right:1.25rem;}"],
  ["py-5", ".py-5{padding-bottom:1.25rem;padding-top:1.25rem;}"],
  ["pt-5", ".pt-5{padding-top:1.25rem;}"],
  ["pr-5", ".pr-5{padding-right:1.25rem;}"],
  ["pb-5", ".pb-5{padding-bottom:1.25rem;}"],
  ["pl-5", ".pl-5{padding-left:1.25rem;}"],
  ["p-6", ".p-6{padding:1.5rem;}"],
  ["px-6", ".px-6{padding-left:1.5rem;padding-right:1.5rem;}"],
  ["py-6", ".py-6{padding-bottom:1.5rem;padding-top:1.5rem;}"],
  ["pt-6", ".pt-6{padding-top:1.5rem;}"],
  ["pr-6", ".pr-6{padding-right:1.5rem;}"],
  ["pb-6", ".pb-6{padding-bottom:1.5rem;}"],
  ["pl-6", ".pl-6{padding-left:1.5rem;}"],
  ["p-7", ".p-7{padding:1.75rem;}"],
  ["px-7", ".px-7{padding-left:1.75rem;padding-right:1.75rem;}"],
  ["py-7", ".py-7{padding-bottom:1.75rem;padding-top:1.75rem;}"],
  ["pt-7", ".pt-7{padding-top:1.75rem;}"],
  ["pr-7", ".pr-7{padding-right:1.75rem;}"],
  ["pb-7", ".pb-7{padding-bottom:1.75rem;}"],
  ["pl-7", ".pl-7{padding-left:1.75rem;}"],
  ["p-8", ".p-8{padding:2rem;}"],
  ["px-8", ".px-8{padding-left:2rem;padding-right:2rem;}"],
  ["py-8", ".py-8{padding-bottom:2rem;padding-top:2rem;}"],
  ["pt-8", ".pt-8{padding-top:2rem;}"],
  ["pr-8", ".pr-8{padding-right:2rem;}"],
  ["pb-8", ".pb-8{padding-bottom:2rem;}"],
  ["pl-8", ".pl-8{padding-left:2rem;}"],
  ["p-9", ".p-9{padding:2.25rem;}"],
  ["px-9", ".px-9{padding-left:2.25rem;padding-right:2.25rem;}"],
  ["py-9", ".py-9{padding-bottom:2.25rem;padding-top:2.25rem;}"],
  ["pt-9", ".pt-9{padding-top:2.25rem;}"],
  ["pr-9", ".pr-9{padding-right:2.25rem;}"],
  ["pb-9", ".pb-9{padding-bottom:2.25rem;}"],
  ["pl-9", ".pl-9{padding-left:2.25rem;}"],
  ["p-10", ".p-10{padding:2.5rem;}"],
  ["px-10", ".px-10{padding-left:2.5rem;padding-right:2.5rem;}"],
  ["py-10", ".py-10{padding-bottom:2.5rem;padding-top:2.5rem;}"],
  ["pt-10", ".pt-10{padding-top:2.5rem;}"],
  ["pr-10", ".pr-10{padding-right:2.5rem;}"],
  ["pb-10", ".pb-10{padding-bottom:2.5rem;}"],
  ["pl-10", ".pl-10{padding-left:2.5rem;}"],
  ["p-11", ".p-11{padding:2.75rem;}"],
  ["px-11", ".px-11{padding-left:2.75rem;padding-right:2.75rem;}"],
  ["py-11", ".py-11{padding-bottom:2.75rem;padding-top:2.75rem;}"],
  ["pt-11", ".pt-11{padding-top:2.75rem;}"],
  ["pr-11", ".pr-11{padding-right:2.75rem;}"],
  ["pb-11", ".pb-11{padding-bottom:2.75rem;}"],
  ["pl-11", ".pl-11{padding-left:2.75rem;}"],
  ["p-12", ".p-12{padding:3rem;}"],
  ["px-12", ".px-12{padding-left:3rem;padding-right:3rem;}"],
  ["py-12", ".py-12{padding-bottom:3rem;padding-top:3rem;}"],
  ["pt-12", ".pt-12{padding-top:3rem;}"],
  ["pr-12", ".pr-12{padding-right:3rem;}"],
  ["pb-12", ".pb-12{padding-bottom:3rem;}"],
  ["pl-12", ".pl-12{padding-left:3rem;}"],
  ["p-14", ".p-14{padding:3.5rem;}"],
  ["px-14", ".px-14{padding-left:3.5rem;padding-right:3.5rem;}"],
  ["py-14", ".py-14{padding-bottom:3.5rem;padding-top:3.5rem;}"],
  ["pt-14", ".pt-14{padding-top:3.5rem;}"],
  ["pr-14", ".pr-14{padding-right:3.5rem;}"],
  ["pb-14", ".pb-14{padding-bottom:3.5rem;}"],
  ["pl-14", ".pl-14{padding-left:3.5rem;}"],
  ["p-16", ".p-16{padding:4rem;}"],
  ["px-16", ".px-16{padding-left:4rem;padding-right:4rem;}"],
  ["py-16", ".py-16{padding-bottom:4rem;padding-top:4rem;}"],
  ["pt-16", ".pt-16{padding-top:4rem;}"],
  ["pr-16", ".pr-16{padding-right:4rem;}"],
  ["pb-16", ".pb-16{padding-bottom:4rem;}"],
  ["pl-16", ".pl-16{padding-left:4rem;}"],
  ["p-20", ".p-20{padding:5rem;}"],
  ["px-20", ".px-20{padding-left:5rem;padding-right:5rem;}"],
  ["py-20", ".py-20{padding-bottom:5rem;padding-top:5rem;}"],
  ["pt-20", ".pt-20{padding-top:5rem;}"],
  ["pr-20", ".pr-20{padding-right:5rem;}"],
  ["pb-20", ".pb-20{padding-bottom:5rem;}"],
  ["pl-20", ".pl-20{padding-left:5rem;}"],
  ["p-24", ".p-24{padding:6rem;}"],
  ["px-24", ".px-24{padding-left:6rem;padding-right:6rem;}"],
  ["py-24", ".py-24{padding-bottom:6rem;padding-top:6rem;}"],
  ["pt-24", ".pt-24{padding-top:6rem;}"],
  ["pr-24", ".pr-24{padding-right:6rem;}"],
  ["pb-24", ".pb-24{padding-bottom:6rem;}"],
  ["pl-24", ".pl-24{padding-left:6rem;}"],
  ["p-28", ".p-28{padding:7rem;}"],
  ["px-28", ".px-28{padding-left:7rem;padding-right:7rem;}"],
  ["py-28", ".py-28{padding-bottom:7rem;padding-top:7rem;}"],
  ["pt-28", ".pt-28{padding-top:7rem;}"],
  ["pr-28", ".pr-28{padding-right:7rem;}"],
  ["pb-28", ".pb-28{padding-bottom:7rem;}"],
  ["pl-28", ".pl-28{padding-left:7rem;}"],
  ["p-32", ".p-32{padding:8rem;}"],
  ["px-32", ".px-32{padding-left:8rem;padding-right:8rem;}"],
  ["py-32", ".py-32{padding-bottom:8rem;padding-top:8rem;}"],
  ["pt-32", ".pt-32{padding-top:8rem;}"],
  ["pr-32", ".pr-32{padding-right:8rem;}"],
  ["pb-32", ".pb-32{padding-bottom:8rem;}"],
  ["pl-32", ".pl-32{padding-left:8rem;}"],
  ["p-36", ".p-36{padding:9rem;}"],
  ["px-36", ".px-36{padding-left:9rem;padding-right:9rem;}"],
  ["py-36", ".py-36{padding-bottom:9rem;padding-top:9rem;}"],
  ["pt-36", ".pt-36{padding-top:9rem;}"],
  ["pr-36", ".pr-36{padding-right:9rem;}"],
  ["pb-36", ".pb-36{padding-bottom:9rem;}"],
  ["pl-36", ".pl-36{padding-left:9rem;}"],
  ["p-40", ".p-40{padding:10rem;}"],
  ["px-40", ".px-40{padding-left:10rem;padding-right:10rem;}"],
  ["py-40", ".py-40{padding-bottom:10rem;padding-top:10rem;}"],
  ["pt-40", ".pt-40{padding-top:10rem;}"],
  ["pr-40", ".pr-40{padding-right:10rem;}"],
  ["pb-40", ".pb-40{padding-bottom:10rem;}"],
  ["pl-40", ".pl-40{padding-left:10rem;}"],
  ["p-44", ".p-44{padding:11rem;}"],
  ["px-44", ".px-44{padding-left:11rem;padding-right:11rem;}"],
  ["py-44", ".py-44{padding-bottom:11rem;padding-top:11rem;}"],
  ["pt-44", ".pt-44{padding-top:11rem;}"],
  ["pr-44", ".pr-44{padding-right:11rem;}"],
  ["pb-44", ".pb-44{padding-bottom:11rem;}"],
  ["pl-44", ".pl-44{padding-left:11rem;}"],
  ["p-48", ".p-48{padding:12rem;}"],
  ["px-48", ".px-48{padding-left:12rem;padding-right:12rem;}"],
  ["py-48", ".py-48{padding-bottom:12rem;padding-top:12rem;}"],
  ["pt-48", ".pt-48{padding-top:12rem;}"],
  ["pr-48", ".pr-48{padding-right:12rem;}"],
  ["pb-48", ".pb-48{padding-bottom:12rem;}"],
  ["pl-48", ".pl-48{padding-left:12rem;}"],
  ["p-52", ".p-52{padding:13rem;}"],
  ["px-52", ".px-52{padding-left:13rem;padding-right:13rem;}"],
  ["py-52", ".py-52{padding-bottom:13rem;padding-top:13rem;}"],
  ["pt-52", ".pt-52{padding-top:13rem;}"],
  ["pr-52", ".pr-52{padding-right:13rem;}"],
  ["pb-52", ".pb-52{padding-bottom:13rem;}"],
  ["pl-52", ".pl-52{padding-left:13rem;}"],
  ["p-56", ".p-56{padding:14rem;}"],
  ["px-56", ".px-56{padding-left:14rem;padding-right:14rem;}"],
  ["py-56", ".py-56{padding-bottom:14rem;padding-top:14rem;}"],
  ["pt-56", ".pt-56{padding-top:14rem;}"],
  ["pr-56", ".pr-56{padding-right:14rem;}"],
  ["pb-56", ".pb-56{padding-bottom:14rem;}"],
  ["pl-56", ".pl-56{padding-left:14rem;}"],
  ["p-60", ".p-60{padding:15rem;}"],
  ["px-60", ".px-60{padding-left:15rem;padding-right:15rem;}"],
  ["py-60", ".py-60{padding-bottom:15rem;padding-top:15rem;}"],
  ["pt-60", ".pt-60{padding-top:15rem;}"],
  ["pr-60", ".pr-60{padding-right:15rem;}"],
  ["pb-60", ".pb-60{padding-bottom:15rem;}"],
  ["pl-60", ".pl-60{padding-left:15rem;}"],
  ["p-64", ".p-64{padding:16rem;}"],
  ["px-64", ".px-64{padding-left:16rem;padding-right:16rem;}"],
  ["py-64", ".py-64{padding-bottom:16rem;padding-top:16rem;}"],
  ["pt-64", ".pt-64{padding-top:16rem;}"],
  ["pr-64", ".pr-64{padding-right:16rem;}"],
  ["pb-64", ".pb-64{padding-bottom:16rem;}"],
  ["pl-64", ".pl-64{padding-left:16rem;}"],
  ["p-72", ".p-72{padding:18rem;}"],
  ["px-72", ".px-72{padding-left:18rem;padding-right:18rem;}"],
  ["py-72", ".py-72{padding-bottom:18rem;padding-top:18rem;}"],
  ["pt-72", ".pt-72{padding-top:18rem;}"],
  ["pr-72", ".pr-72{padding-right:18rem;}"],
  ["pb-72", ".pb-72{padding-bottom:18rem;}"],
  ["pl-72", ".pl-72{padding-left:18rem;}"],
  ["p-80", ".p-80{padding:20rem;}"],
  ["px-80", ".px-80{padding-left:20rem;padding-right:20rem;}"],
  ["py-80", ".py-80{padding-bottom:20rem;padding-top:20rem;}"],
  ["pt-80", ".pt-80{padding-top:20rem;}"],
  ["pr-80", ".pr-80{padding-right:20rem;}"],
  ["pb-80", ".pb-80{padding-bottom:20rem;}"],
  ["pl-80", ".pl-80{padding-left:20rem;}"],
  ["p-96", ".p-96{padding:24rem;}"],
  ["px-96", ".px-96{padding-left:24rem;padding-right:24rem;}"],
  ["py-96", ".py-96{padding-bottom:24rem;padding-top:24rem;}"],
  ["pt-96", ".pt-96{padding-top:24rem;}"],
  ["pr-96", ".pr-96{padding-right:24rem;}"],
  ["pb-96", ".pb-96{padding-bottom:24rem;}"],
  ["pl-96", ".pl-96{padding-left:24rem;}"],
  ["p-auto", ".p-auto{padding:auto;}"],
  ["px-auto", ".px-auto{padding-left:auto;padding-right:auto;}"],
  ["py-auto", ".py-auto{padding-bottom:auto;padding-top:auto;}"],
  ["pt-auto", ".pt-auto{padding-top:auto;}"],
  ["pr-auto", ".pr-auto{padding-right:auto;}"],
  ["pb-auto", ".pb-auto{padding-bottom:auto;}"],
  ["pl-auto", ".pl-auto{padding-left:auto;}"],
  ["pl-auto", ".pl-auto{padding-left:auto;}"],
  ["p-0.5", ".p-0\\.5{padding:0.125rem;}"],
  ["px-0.5", ".px-0\\.5{padding-left:0.125rem;padding-right:0.125rem;}"],
  ["py-0.5", ".py-0\\.5{padding-bottom:0.125rem;padding-top:0.125rem;}"],
  ["pt-0.5", ".pt-0\\.5{padding-top:0.125rem;}"],
  ["pr-0.5", ".pr-0\\.5{padding-right:0.125rem;}"],
  ["pb-0.5", ".pb-0\\.5{padding-bottom:0.125rem;}"],
  ["pl-0.5", ".pl-0\\.5{padding-left:0.125rem;}"],
  ["p-1.5", ".p-1\\.5{padding:0.375rem;}"],
  ["px-1.5", ".px-1\\.5{padding-left:0.375rem;padding-right:0.375rem;}"],
  ["py-1.5", ".py-1\\.5{padding-bottom:0.375rem;padding-top:0.375rem;}"],
  ["pt-1.5", ".pt-1\\.5{padding-top:0.375rem;}"],
  ["pr-1.5", ".pr-1\\.5{padding-right:0.375rem;}"],
  ["pb-1.5", ".pb-1\\.5{padding-bottom:0.375rem;}"],
  ["pl-1.5", ".pl-1\\.5{padding-left:0.375rem;}"],
  ["p-2.5", ".p-2\\.5{padding:0.625rem;}"],
  ["px-2.5", ".px-2\\.5{padding-left:0.625rem;padding-right:0.625rem;}"],
  ["py-2.5", ".py-2\\.5{padding-bottom:0.625rem;padding-top:0.625rem;}"],
  ["pt-2.5", ".pt-2\\.5{padding-top:0.625rem;}"],
  ["pr-2.5", ".pr-2\\.5{padding-right:0.625rem;}"],
  ["pb-2.5", ".pb-2\\.5{padding-bottom:0.625rem;}"],
  ["pl-2.5", ".pl-2\\.5{padding-left:0.625rem;}"],
  ["p-3.5", ".p-3\\.5{padding:0.875rem;}"],
  ["px-3.5", ".px-3\\.5{padding-left:0.875rem;padding-right:0.875rem;}"],
  ["py-3.5", ".py-3\\.5{padding-bottom:0.875rem;padding-top:0.875rem;}"],
  ["pt-3.5", ".pt-3\\.5{padding-top:0.875rem;}"],
  ["pr-3.5", ".pr-3\\.5{padding-right:0.875rem;}"],
  ["pb-3.5", ".pb-3\\.5{padding-bottom:0.875rem;}"],
  ["pl-3.5", ".pl-3\\.5{padding-left:0.875rem;}"],
  ["p-[1px]", ".p-\\[1px\\]{padding:1px;}"],
  ["px-[1px]", ".px-\\[1px\\]{padding-left:1px;padding-right:1px;}"],
  ["py-[1px]", ".py-\\[1px\\]{padding-bottom:1px;padding-top:1px;}"],
  ["pt-[1px]", ".pt-\\[1px\\]{padding-top:1px;}"],
  ["pl-[1px]", ".pl-\\[1px\\]{padding-left:1px;}"],
  ["pb-[1px]", ".pb-\\[1px\\]{padding-bottom:1px;}"],
  ["pr-[1px]", ".pr-\\[1px\\]{padding-right:1px;}"],
  ["w-0.5", ".w-0\\.5{width:0.125rem;}"],
  ["w-1.5", ".w-1\\.5{width:0.375rem;}"],
  ["w-2.5", ".w-2\\.5{width:0.625rem;}"],
  ["w-3.5", ".w-3\\.5{width:0.875rem;}"],
  ["w-0", ".w-0{width:0px;}"],
  ["w-px", ".w-px{width:1px;}"],
  ["w-1", ".w-1{width:0.25rem;}"],
  ["w-2", ".w-2{width:0.5rem;}"],
  ["w-3", ".w-3{width:0.75rem;}"],
  ["w-4", ".w-4{width:1rem;}"],
  ["w-5", ".w-5{width:1.25rem;}"],
  ["w-6", ".w-6{width:1.5rem;}"],
  ["w-7", ".w-7{width:1.75rem;}"],
  ["w-8", ".w-8{width:2rem;}"],
  ["w-9", ".w-9{width:2.25rem;}"],
  ["w-10", ".w-10{width:2.5rem;}"],
  ["w-11", ".w-11{width:2.75rem;}"],
  ["w-12", ".w-12{width:3rem;}"],
  ["w-14", ".w-14{width:3.5rem;}"],
  ["w-16", ".w-16{width:4rem;}"],
  ["w-20", ".w-20{width:5rem;}"],
  ["w-24", ".w-24{width:6rem;}"],
  ["w-28", ".w-28{width:7rem;}"],
  ["w-32", ".w-32{width:8rem;}"],
  ["w-36", ".w-36{width:9rem;}"],
  ["w-40", ".w-40{width:10rem;}"],
  ["w-44", ".w-44{width:11rem;}"],
  ["w-48", ".w-48{width:12rem;}"],
  ["w-52", ".w-52{width:13rem;}"],
  ["w-56", ".w-56{width:14rem;}"],
  ["w-60", ".w-60{width:15rem;}"],
  ["w-64", ".w-64{width:16rem;}"],
  ["w-72", ".w-72{width:18rem;}"],
  ["w-80", ".w-80{width:20rem;}"],
  ["w-96", ".w-96{width:24rem;}"],
  ["w-auto", ".w-auto{width:auto;}"],
  ["w-full", ".w-full{width:100%;}"],
  ["w-screen", ".w-screen{width:100vw;}"],
  ["w-min", ".w-min{width:min-content;}"],
  ["w-max", ".w-max{width:max-content;}"],
  ["w-fit", ".w-fit{width:fit-content;}"],
  ["w-1/2", ".w-1\\/2{width:50%;}"],
  ["w-1/3", ".w-1\\/3{width:33.33333333333333%;}"],
  ["w-2/3", ".w-2\\/3{width:66.66666666666666%;}"],
  ["w-1/4", ".w-1\\/4{width:25%;}"],
  ["w-2/4", ".w-2\\/4{width:50%;}"],
  ["w-3/4", ".w-3\\/4{width:75%;}"],
  ["w-1/5", ".w-1\\/5{width:20%;}"],
  ["w-2/5", ".w-2\\/5{width:40%;}"],
  ["w-3/5", ".w-3\\/5{width:60%;}"],
  ["w-4/5", ".w-4\\/5{width:80%;}"],
  ["w-1/6", ".w-1\\/6{width:16.666666666666664%;}"],
  ["w-2/6", ".w-2\\/6{width:33.33333333333333%;}"],
  ["w-3/6", ".w-3\\/6{width:50%;}"],
  ["w-4/6", ".w-4\\/6{width:66.66666666666666%;}"],
  ["w-5/6", ".w-5\\/6{width:83.33333333333334%;}"],
  ["w-1/12", ".w-1\\/12{width:8.333333333333332%;}"],
  ["w-2/12", ".w-2\\/12{width:16.666666666666664%;}"],
  ["w-3/12", ".w-3\\/12{width:25%;}"],
  ["w-4/12", ".w-4\\/12{width:33.33333333333333%;}"],
  ["w-5/12", ".w-5\\/12{width:41.66666666666667%;}"],
  ["w-6/12", ".w-6\\/12{width:50%;}"],
  ["w-7/12", ".w-7\\/12{width:58.333333333333336%;}"],
  ["w-8/12", ".w-8\\/12{width:66.66666666666666%;}"],
  ["w-9/12", ".w-9\\/12{width:75%;}"],
  ["w-10/12", ".w-10\\/12{width:83.33333333333334%;}"],
  ["w-11/12", ".w-11\\/12{width:91.66666666666666%;}"],
  ["w-[1rem]", ".w-\\[1rem\\]{width:1rem;}"],
  ["min-w-0", ".min-w-0{min-width:0px;}"],
  ["min-w-full", ".min-w-full{min-width:100%;}"],
  ["min-w-min", ".min-w-min{min-width:min-content;}"],
  ["min-w-max", ".min-w-max{min-width:max-content;}"],
  ["min-w-fit", ".min-w-fit{min-width:fit-content;}"],
  ["max-w-0", ".max-w-0{max-width:0rem;}"],
  ["max-w-none", ".max-w-none{max-width:none;}"],
  ["max-w-xs", ".max-w-xs{max-width:20rem;}"],
  ["max-w-sm", ".max-w-sm{max-width:24rem;}"],
  ["max-w-md", ".max-w-md{max-width:28rem;}"],
  ["max-w-lg", ".max-w-lg{max-width:32rem;}"],
  ["max-w-xl", ".max-w-xl{max-width:36rem;}"],
  ["max-w-2xl", ".max-w-2xl{max-width:42rem;}"],
  ["max-w-3xl", ".max-w-3xl{max-width:48rem;}"],
  ["max-w-4xl", ".max-w-4xl{max-width:56rem;}"],
  ["max-w-5xl", ".max-w-5xl{max-width:64rem;}"],
  ["max-w-6xl", ".max-w-6xl{max-width:72rem;}"],
  ["max-w-7xl", ".max-w-7xl{max-width:80rem;}"],
  ["max-w-full", ".max-w-full{max-width:100%;}"],
  ["max-w-min", ".max-w-min{max-width:min-content;}"],
  ["max-w-max", ".max-w-max{max-width:max-content;}"],
  ["max-w-fit", ".max-w-fit{max-width:fit-content;}"],
  ["max-w-prose", ".max-w-prose{max-width:65ch;}"],
  ["max-w-screen-sm", ".max-w-screen-sm{max-width:640px;}"],
  ["max-w-screen-md", ".max-w-screen-md{max-width:768px;}"],
  ["max-w-screen-lg", ".max-w-screen-lg{max-width:1024px;}"],
  ["max-w-screen-xl", ".max-w-screen-xl{max-width:1280px;}"],
  ["max-w-screen-2xl", ".max-w-screen-2xl{max-width:1536px;}"],
  ["h-5/6", ".h-5\\/6{height:83.33333333333334%;}"],
  ["h-full", ".h-full{height:100%;}"],
  ["h-screen", ".h-screen{height:100vh;}"],
  ["h-min", ".h-min{height:min-content;}"],
  ["h-max", ".h-max{height:max-content;}"],
  ["h-fit", ".h-fit{height:fit-content;}"],
  ["max-h-0.5", ".max-h-0\\.5{max-height:0.125rem;}"],
  ["max-h-1.5", ".max-h-1\\.5{max-height:0.375rem;}"],
  ["max-h-2.5", ".max-h-2\\.5{max-height:0.625rem;}"],
  ["max-h-3.5", ".max-h-3\\.5{max-height:0.875rem;}"],
  ["max-h-0", ".max-h-0{max-height:0px;}"],
  ["max-h-px", ".max-h-px{max-height:1px;}"],
  ["max-h-1", ".max-h-1{max-height:0.25rem;}"],
  ["max-h-2", ".max-h-2{max-height:0.5rem;}"],
  ["max-h-3", ".max-h-3{max-height:0.75rem;}"],
  ["max-h-4", ".max-h-4{max-height:1rem;}"],
  ["max-h-5", ".max-h-5{max-height:1.25rem;}"],
  ["max-h-6", ".max-h-6{max-height:1.5rem;}"],
  ["max-h-7", ".max-h-7{max-height:1.75rem;}"],
  ["max-h-8", ".max-h-8{max-height:2rem;}"],
  ["max-h-9", ".max-h-9{max-height:2.25rem;}"],
  ["max-h-10", ".max-h-10{max-height:2.5rem;}"],
  ["max-h-11", ".max-h-11{max-height:2.75rem;}"],
  ["max-h-12", ".max-h-12{max-height:3rem;}"],
  ["max-h-14", ".max-h-14{max-height:3.5rem;}"],
  ["max-h-16", ".max-h-16{max-height:4rem;}"],
  ["max-h-20", ".max-h-20{max-height:5rem;}"],
  ["max-h-24", ".max-h-24{max-height:6rem;}"],
  ["max-h-28", ".max-h-28{max-height:7rem;}"],
  ["max-h-32", ".max-h-32{max-height:8rem;}"],
  ["max-h-36", ".max-h-36{max-height:9rem;}"],
  ["max-h-40", ".max-h-40{max-height:10rem;}"],
  ["max-h-44", ".max-h-44{max-height:11rem;}"],
  ["max-h-48", ".max-h-48{max-height:12rem;}"],
  ["max-h-52", ".max-h-52{max-height:13rem;}"],
  ["max-h-56", ".max-h-56{max-height:14rem;}"],
  ["max-h-60", ".max-h-60{max-height:15rem;}"],
  ["max-h-64", ".max-h-64{max-height:16rem;}"],
  ["max-h-72", ".max-h-72{max-height:18rem;}"],
  ["max-h-80", ".max-h-80{max-height:20rem;}"],
  ["max-h-96", ".max-h-96{max-height:24rem;}"],
  ["max-h-full", ".max-h-full{max-height:100%;}"],
  ["max-h-screen", ".max-h-screen{max-height:100vh;}"],
  ["max-h-min", ".max-h-min{max-height:min-content;}"],
  ["max-h-max", ".max-h-max{max-height:max-content;}"],
  ["max-h-fit", ".max-h-fit{max-height:fit-content;}"],
  ["text-xs", ".text-xs{font-size:0.75rem;line-height:1rem;}"],
  ["text-sm", ".text-sm{font-size:0.875rem;line-height:1.25rem;}"],
  ["text-base", ".text-base{font-size:1rem;line-height:1.5rem;}"],
  ["text-lg", ".text-lg{font-size:1.125rem;line-height:1.75rem;}"],
  ["text-xl", ".text-xl{font-size:1.25rem;line-height:1.75rem;}"],
  ["text-2xl", ".text-2xl{font-size:1.5rem;line-height:2rem;}"],
  ["text-3xl", ".text-3xl{font-size:1.875rem;line-height:2.25rem;}"],
  ["text-4xl", ".text-4xl{font-size:2.25rem;line-height:2.5rem;}"],
  ["text-5xl", ".text-5xl{font-size:3rem;line-height:1;}"],
  ["text-6xl", ".text-6xl{font-size:3.75rem;line-height:1;}"],
  ["text-7xl", ".text-7xl{font-size:4.5rem;line-height:1;}"],
  ["text-8xl", ".text-8xl{font-size:6rem;line-height:1;}"],
  ["text-9xl", ".text-9xl{font-size:8rem;line-height:1;}"],
  [
    "antialiased",
    ".antialiased{-moz-osx-font-smoothing:grayscale;-webkit-font-smoothing:antialiased;}",
  ],
  [
    "subpixel-antialiased",
    ".subpixel-antialiased{-moz-osx-font-smoothing:auto;-webkit-font-smoothing:auto;}",
  ],
  ["italic", ".italic{font-style:italic;}"],
  ["not-italic", ".not-italic{font-style:normal;}"],
  ["font-thin", ".font-thin{font-weight:100;}"],
  ["font-extralight", ".font-extralight{font-weight:200;}"],
  ["font-light", ".font-light{font-weight:300;}"],
  ["font-normal", ".font-normal{font-weight:400;}"],
  ["font-medium", ".font-medium{font-weight:500;}"],
  ["font-semibold", ".font-semibold{font-weight:600;}"],
  ["font-bold", ".font-bold{font-weight:700;}"],
  ["font-extrabold", ".font-extrabold{font-weight:800;}"],
  ["font-black", ".font-black{font-weight:900;}"],
  [
    "font-sans",
    `.font-sans{font-family:ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";}`,
  ],
  [
    "font-serif",
    `.font-serif{font-family:ui-serif, Georgia, Cambria, "Times New Roman", Times, serif;}`,
  ],
  [
    "font-mono",
    `.font-mono{font-family:ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;}`,
  ],
  ["tracking-tighter", ".tracking-tighter{letter-spacing:-0.05em;}"],
  ["tracking-tight", ".tracking-tight{letter-spacing:-0.025em;}"],
  ["tracking-normal", ".tracking-normal{letter-spacing:0em;}"],
  ["tracking-wide", ".tracking-wide{letter-spacing:0.025em;}"],
  ["tracking-wider", ".tracking-wider{letter-spacing:0.05em;}"],
  ["tracking-widest", ".tracking-widest{letter-spacing:0.1em;}"],
  ["leading-3", ".leading-3{line-height:0.75rem;}"],
  ["leading-4", ".leading-4{line-height:1rem;}"],
  ["leading-5", ".leading-5{line-height:1.25rem;}"],
  ["leading-6", ".leading-6{line-height:1.5rem;}"],
  ["leading-7", ".leading-7{line-height:1.75rem;}"],
  ["leading-8", ".leading-8{line-height:2rem;}"],
  ["leading-9", ".leading-9{line-height:2.25rem;}"],
  ["leading-10", ".leading-10{line-height:2.5rem;}"],
  ["leading-none", ".leading-none{line-height:1;}"],
  ["leading-tight", ".leading-tight{line-height:1.25;}"],
  ["leading-snug", ".leading-snug{line-height:1.375;}"],
  ["leading-normal", ".leading-normal{line-height:1.5;}"],
  ["leading-relaxed", ".leading-relaxed{line-height:1.625;}"],
  ["leading-loose", ".leading-loose{line-height:2;}"],
  ["text-left", ".text-left{text-align:left;}"],
  ["text-center", ".text-center{text-align:center;}"],
  ["text-right", ".text-right{text-align:right;}"],
  ["text-justify", ".text-justify{text-align:justify;}"],
  ["underline", ".underline{text-decoration-line:underline;}"],
  ["overline", ".overline{text-decoration-line:overline;}"],
  ["line-through", ".line-through{text-decoration-line:line-through;}"],
  ["no-underline", ".no-underline{text-decoration-line:none;}"],
  ["align-baseline", ".align-baseline{vertical-align:baseline;}"],
  ["align-top", ".align-top{vertical-align:top;}"],
  ["align-middle", ".align-middle{vertical-align:middle;}"],
  ["align-bottom", ".align-bottom{vertical-align:bottom;}"],
  ["align-text-top", ".align-text-top{vertical-align:text-top;}"],
  ["align-text-bottom", ".align-text-bottom{vertical-align:text-bottom;}"],
  ["align-sub", ".align-sub{vertical-align:sub;}"],
  ["align-super", ".align-super{vertical-align:super;}"],
  ["whitespace-normal", ".whitespace-normal{white-space:normal;}"],
  ["whitespace-nowrap", ".whitespace-nowrap{white-space:nowrap;}"],
  ["whitespace-pre", ".whitespace-pre{white-space:pre;}"],
  ["whitespace-pre-line", ".whitespace-pre-line{white-space:pre-line;}"],
  ["whitespace-pre-wrap", ".whitespace-pre-wrap{white-space:pre-wrap;}"],
  ["break-normal", ".break-normal{overflow-wrap:normal;word-break:normal;}"],
  ["break-words", ".break-words{overflow-wrap:break-word;}"],
  ["break-all", ".break-all{word-break:break-all;}"],
  ["content-none", ".content-none{content:none;}"],

  ["rounded", ".rounded{border-radius:0.25rem;}"],
  ["rounded-none", ".rounded-none{border-radius:0px;}"],
  ["rounded-sm", ".rounded-sm{border-radius:0.125rem;}"],
  ["rounded-md", ".rounded-md{border-radius:0.375rem;}"],
  ["rounded-lg", ".rounded-lg{border-radius:0.5rem;}"],
  ["rounded-xl", ".rounded-xl{border-radius:0.75rem;}"],
  ["rounded-2xl", ".rounded-2xl{border-radius:1rem;}"],
  ["rounded-3xl", ".rounded-3xl{border-radius:1.5rem;}"],
  ["rounded-full", ".rounded-full{border-radius:9999px;}"],
  [
    "rounded-t",
    ".rounded-t{border-top-left-radius:0.25rem;border-top-right-radius:0.25rem;}",
  ],
  [
    "rounded-r",
    ".rounded-r{border-bottom-right-radius:0.25rem;border-top-right-radius:0.25rem;}",
  ],
  [
    "rounded-b",
    ".rounded-b{border-bottom-left-radius:0.25rem;border-bottom-right-radius:0.25rem;}",
  ],
  [
    "rounded-l",
    ".rounded-l{border-bottom-left-radius:0.25rem;border-top-left-radius:0.25rem;}",
  ],
  ["rounded-tr", ".rounded-tr{border-top-right-radius:0.25rem;}"],
  ["rounded-br", ".rounded-br{border-bottom-right-radius:0.25rem;}"],
  ["rounded-bl", ".rounded-bl{border-bottom-left-radius:0.25rem;}"],
  ["rounded-tl", ".rounded-tl{border-top-left-radius:0.25rem;}"],
  [
    "rounded-t-none",
    ".rounded-t-none{border-top-left-radius:0px;border-top-right-radius:0px;}",
  ],
  [
    "rounded-t-sm",
    ".rounded-t-sm{border-top-left-radius:0.125rem;border-top-right-radius:0.125rem;}",
  ],
  [
    "rounded-t-md",
    ".rounded-t-md{border-top-left-radius:0.375rem;border-top-right-radius:0.375rem;}",
  ],
  [
    "rounded-t-lg",
    ".rounded-t-lg{border-top-left-radius:0.5rem;border-top-right-radius:0.5rem;}",
  ],
  [
    "rounded-t-xl",
    ".rounded-t-xl{border-top-left-radius:0.75rem;border-top-right-radius:0.75rem;}",
  ],
  [
    "rounded-t-2xl",
    ".rounded-t-2xl{border-top-left-radius:1rem;border-top-right-radius:1rem;}",
  ],
  [
    "rounded-t-3xl",
    ".rounded-t-3xl{border-top-left-radius:1.5rem;border-top-right-radius:1.5rem;}",
  ],
  [
    "rounded-t-full",
    ".rounded-t-full{border-top-left-radius:9999px;border-top-right-radius:9999px;}",
  ],
  [
    "rounded-r-none",
    ".rounded-r-none{border-bottom-right-radius:0px;border-top-right-radius:0px;}",
  ],
  [
    "rounded-r-sm",
    ".rounded-r-sm{border-bottom-right-radius:0.125rem;border-top-right-radius:0.125rem;}",
  ],
  [
    "rounded-r-md",
    ".rounded-r-md{border-bottom-right-radius:0.375rem;border-top-right-radius:0.375rem;}",
  ],
  [
    "rounded-r-lg",
    ".rounded-r-lg{border-bottom-right-radius:0.5rem;border-top-right-radius:0.5rem;}",
  ],
  [
    "rounded-r-xl",
    ".rounded-r-xl{border-bottom-right-radius:0.75rem;border-top-right-radius:0.75rem;}",
  ],
  [
    "rounded-r-2xl",
    ".rounded-r-2xl{border-bottom-right-radius:1rem;border-top-right-radius:1rem;}",
  ],
  [
    "rounded-r-3xl",
    ".rounded-r-3xl{border-bottom-right-radius:1.5rem;border-top-right-radius:1.5rem;}",
  ],
  [
    "rounded-r-full",
    ".rounded-r-full{border-bottom-right-radius:9999px;border-top-right-radius:9999px;}",
  ],
  [
    "rounded-b-none",
    ".rounded-b-none{border-bottom-left-radius:0px;border-bottom-right-radius:0px;}",
  ],
  [
    "rounded-b-sm",
    ".rounded-b-sm{border-bottom-left-radius:0.125rem;border-bottom-right-radius:0.125rem;}",
  ],
  [
    "rounded-b-md",
    ".rounded-b-md{border-bottom-left-radius:0.375rem;border-bottom-right-radius:0.375rem;}",
  ],
  [
    "rounded-b-lg",
    ".rounded-b-lg{border-bottom-left-radius:0.5rem;border-bottom-right-radius:0.5rem;}",
  ],
  [
    "rounded-b-xl",
    ".rounded-b-xl{border-bottom-left-radius:0.75rem;border-bottom-right-radius:0.75rem;}",
  ],
  [
    "rounded-b-2xl",
    ".rounded-b-2xl{border-bottom-left-radius:1rem;border-bottom-right-radius:1rem;}",
  ],
  [
    "rounded-b-3xl",
    ".rounded-b-3xl{border-bottom-left-radius:1.5rem;border-bottom-right-radius:1.5rem;}",
  ],
  [
    "rounded-b-full",
    ".rounded-b-full{border-bottom-left-radius:9999px;border-bottom-right-radius:9999px;}",
  ],
  [
    "rounded-l-none",
    ".rounded-l-none{border-bottom-left-radius:0px;border-top-left-radius:0px;}",
  ],
  [
    "rounded-l-sm",
    ".rounded-l-sm{border-bottom-left-radius:0.125rem;border-top-left-radius:0.125rem;}",
  ],
  [
    "rounded-l-md",
    ".rounded-l-md{border-bottom-left-radius:0.375rem;border-top-left-radius:0.375rem;}",
  ],
  [
    "rounded-l-lg",
    ".rounded-l-lg{border-bottom-left-radius:0.5rem;border-top-left-radius:0.5rem;}",
  ],
  [
    "rounded-l-xl",
    ".rounded-l-xl{border-bottom-left-radius:0.75rem;border-top-left-radius:0.75rem;}",
  ],
  [
    "rounded-l-2xl",
    ".rounded-l-2xl{border-bottom-left-radius:1rem;border-top-left-radius:1rem;}",
  ],
  [
    "rounded-l-3xl",
    ".rounded-l-3xl{border-bottom-left-radius:1.5rem;border-top-left-radius:1.5rem;}",
  ],
  [
    "rounded-l-full",
    ".rounded-l-full{border-bottom-left-radius:9999px;border-top-left-radius:9999px;}",
  ],
  ["rounded-tl-none", ".rounded-tl-none{border-top-left-radius:0px;}"],
  ["rounded-tl-sm", ".rounded-tl-sm{border-top-left-radius:0.125rem;}"],
  ["rounded-tl-md", ".rounded-tl-md{border-top-left-radius:0.375rem;}"],
  ["rounded-tl-lg", ".rounded-tl-lg{border-top-left-radius:0.5rem;}"],
  ["rounded-tl-xl", ".rounded-tl-xl{border-top-left-radius:0.75rem;}"],
  ["rounded-tl-2xl", ".rounded-tl-2xl{border-top-left-radius:1rem;}"],
  ["rounded-tl-3xl", ".rounded-tl-3xl{border-top-left-radius:1.5rem;}"],
  ["rounded-tl-full", ".rounded-tl-full{border-top-left-radius:9999px;}"],
  ["rounded-tr-none", ".rounded-tr-none{border-top-right-radius:0px;}"],
  ["rounded-tr-sm", ".rounded-tr-sm{border-top-right-radius:0.125rem;}"],
  ["rounded-tr-md", ".rounded-tr-md{border-top-right-radius:0.375rem;}"],
  ["rounded-tr-lg", ".rounded-tr-lg{border-top-right-radius:0.5rem;}"],
  ["rounded-tr-xl", ".rounded-tr-xl{border-top-right-radius:0.75rem;}"],
  ["rounded-tr-2xl", ".rounded-tr-2xl{border-top-right-radius:1rem;}"],
  ["rounded-tr-3xl", ".rounded-tr-3xl{border-top-right-radius:1.5rem;}"],
  ["rounded-tr-full", ".rounded-tr-full{border-top-right-radius:9999px;}"],
  ["rounded-br-none", ".rounded-br-none{border-bottom-right-radius:0px;}"],
  ["rounded-br-sm", ".rounded-br-sm{border-bottom-right-radius:0.125rem;}"],
  ["rounded-br-md", ".rounded-br-md{border-bottom-right-radius:0.375rem;}"],
  ["rounded-br-lg", ".rounded-br-lg{border-bottom-right-radius:0.5rem;}"],
  ["rounded-br-xl", ".rounded-br-xl{border-bottom-right-radius:0.75rem;}"],
  ["rounded-br-2xl", ".rounded-br-2xl{border-bottom-right-radius:1rem;}"],
  ["rounded-br-3xl", ".rounded-br-3xl{border-bottom-right-radius:1.5rem;}"],
  ["rounded-br-full", ".rounded-br-full{border-bottom-right-radius:9999px;}"],
  ["rounded-bl-none", ".rounded-bl-none{border-bottom-left-radius:0px;}"],
  ["rounded-bl-sm", ".rounded-bl-sm{border-bottom-left-radius:0.125rem;}"],
  ["rounded-bl-md", ".rounded-bl-md{border-bottom-left-radius:0.375rem;}"],
  ["rounded-bl-lg", ".rounded-bl-lg{border-bottom-left-radius:0.5rem;}"],
  ["rounded-bl-xl", ".rounded-bl-xl{border-bottom-left-radius:0.75rem;}"],
  ["rounded-bl-2xl", ".rounded-bl-2xl{border-bottom-left-radius:1rem;}"],
  ["rounded-bl-3xl", ".rounded-bl-3xl{border-bottom-left-radius:1.5rem;}"],
  ["rounded-bl-full", ".rounded-bl-full{border-bottom-left-radius:9999px;}"],
  ["border", ".border{border-width:1px;}"],
  ["border-0", ".border-0{border-width:0px;}"],
  ["border-2", ".border-2{border-width:2px;}"],
  ["border-4", ".border-4{border-width:4px;}"],
  ["border-8", ".border-8{border-width:8px;}"],
  ["border-x", ".border-x{border-left-width:1px;border-right-width:1px;}"],
  ["border-y", ".border-y{border-bottom-width:1px;border-top-width:1px;}"],
  ["border-t", ".border-t{border-top-width:1px;}"],
  ["border-r", ".border-r{border-right-width:1px;}"],
  ["border-b", ".border-b{border-bottom-width:1px;}"],
  ["border-l", ".border-l{border-left-width:1px;}"],
  ["border-x-0", ".border-x-0{border-left-width:0px;border-right-width:0px;}"],
  ["border-x-2", ".border-x-2{border-left-width:2px;border-right-width:2px;}"],
  ["border-x-4", ".border-x-4{border-left-width:4px;border-right-width:4px;}"],
  ["border-x-8", ".border-x-8{border-left-width:8px;border-right-width:8px;}"],
  ["border-y-0", ".border-y-0{border-bottom-width:0px;border-top-width:0px;}"],
  ["border-y-2", ".border-y-2{border-bottom-width:2px;border-top-width:2px;}"],
  ["border-y-4", ".border-y-4{border-bottom-width:4px;border-top-width:4px;}"],
  ["border-y-8", ".border-y-8{border-bottom-width:8px;border-top-width:8px;}"],
  ["border-t-0", ".border-t-0{border-top-width:0px;}"],
  ["border-t-2", ".border-t-2{border-top-width:2px;}"],
  ["border-t-4", ".border-t-4{border-top-width:4px;}"],
  ["border-t-8", ".border-t-8{border-top-width:8px;}"],
  ["border-r-0", ".border-r-0{border-right-width:0px;}"],
  ["border-r-2", ".border-r-2{border-right-width:2px;}"],
  ["border-r-4", ".border-r-4{border-right-width:4px;}"],
  ["border-r-8", ".border-r-8{border-right-width:8px;}"],
  ["border-b-0", ".border-b-0{border-bottom-width:0px;}"],
  ["border-b-2", ".border-b-2{border-bottom-width:2px;}"],
  ["border-b-4", ".border-b-4{border-bottom-width:4px;}"],
  ["border-b-8", ".border-b-8{border-bottom-width:8px;}"],
  ["border-l-0", ".border-l-0{border-left-width:0px;}"],
  ["border-l-2", ".border-l-2{border-left-width:2px;}"],
  ["border-l-4", ".border-l-4{border-left-width:4px;}"],
  ["border-l-8", ".border-l-8{border-left-width:8px;}"],
  ["border-solid", ".border-solid{border-style:solid;}"],
  ["border-dashed", ".border-dashed{border-style:dashed;}"],
  ["border-dotted", ".border-dotted{border-style:dotted;}"],
  ["border-double", ".border-double{border-style:double;}"],
  ["border-hidden", ".border-hidden{border-style:hidden;}"],
  ["border-none", ".border-none{border-style:none;}"],
  ["outline-0", ".outline-0{outline-width:0px;}"],
  ["outline-1", ".outline-1{outline-width:1px;}"],
  ["outline-2", ".outline-2{outline-width:2px;}"],
  ["outline-4", ".outline-4{outline-width:4px;}"],
  ["outline-8", ".outline-8{outline-width:8px;}"],
  ["outline", ".outline{outline-style:solid;}"],
  [
    "outline-none",
    ".outline-none{outline:2px solid transparent;outline-offset:2px;}",
  ],
  ["outline-dashed", ".outline-dashed{outline-style:dashed;}"],
  ["outline-dotted", ".outline-dotted{outline-style:dotted;}"],
  ["outline-double", ".outline-double{outline-style:double;}"],
  ["outline-hidden", ".outline-hidden{outline-style:hidden;}"],
  ["outline-offset-0", ".outline-offset-0{outline-offset:0px;}"],
  ["outline-offset-1", ".outline-offset-1{outline-offset:1px;}"],
  ["outline-offset-2", ".outline-offset-2{outline-offset:2px;}"],
  ["outline-offset-4", ".outline-offset-4{outline-offset:4px;}"],
  ["outline-offset-8", ".outline-offset-8{outline-offset:8px;}"],
  ["border-collapse", ".border-collapse{border-collapse:collapse;}"],
  ["border-separate", ".border-separate{border-collapse:separate;}"],
  ["opacity-0", ".opacity-0{opacity:0;}"],
  ["opacity-5", ".opacity-5{opacity:0.05;}"],
  ["opacity-10", ".opacity-10{opacity:0.1;}"],
  ["opacity-20", ".opacity-20{opacity:0.2;}"],
  ["opacity-25", ".opacity-25{opacity:0.25;}"],
  ["opacity-30", ".opacity-30{opacity:0.3;}"],
  ["opacity-40", ".opacity-40{opacity:0.4;}"],
  ["opacity-50", ".opacity-50{opacity:0.5;}"],
  ["opacity-60", ".opacity-60{opacity:0.6;}"],
  ["opacity-70", ".opacity-70{opacity:0.7;}"],
  ["opacity-75", ".opacity-75{opacity:0.75;}"],
  ["opacity-80", ".opacity-80{opacity:0.8;}"],
  ["opacity-90", ".opacity-90{opacity:0.9;}"],
  ["opacity-95", ".opacity-95{opacity:0.95;}"],
  ["opacity-100", ".opacity-100{opacity:1;}"],
  ["dark:block", ".dark .dark\\:block{display:block;}"],
];

const config = { theme, mapperMap, modifierMap };

test("presetTw", () => {
  expects.forEach(([className, result]) => {
    expect(generate(config, new Set([className])).css).toBe(
      result,
    );
  });
});
