name: test

on:
  push:
    paths-ignore:
      - '_docs/**'
  schedule:
    - cron:  '* 9 * * *'
jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, macos-latest, windows-latest]
        deno: [v1.x, canary, 1.18.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Lint
        run: |
          deno fmt --check
          deno lint

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, macos-latest, windows-latest]
        deno: [v1.x, canary, 1.18.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Test
        run: deno test --unstable --allow-read --ignore=node_modules,_docs,_examples --import-map=test_import_map.json --doc
